// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/snglrt_spc_bk.tga
gfx/env/snglrt_spc_dn.tga
gfx/env/snglrt_spc_ft.tga
gfx/env/snglrt_spc_lf.tga
gfx/env/snglrt_spc_rt.tga
gfx/env/snglrt_spc_up.tga
kez_singularity.wad
models/kezaeiv/custom_weapons/ammo/amrclip.mdl
models/kezaeiv/custom_weapons/ammo/arrows.mdl
models/kezaeiv/custom_weapons/ammo/bullets.mdl
models/kezaeiv/custom_weapons/ammo/darkmatter.mdl
models/kezaeiv/custom_weapons/ammo/erholungszelle.mdl
models/kezaeiv/custom_weapons/ammo/freedomclip.mdl
models/kezaeiv/custom_weapons/ammo/grenades.mdl
models/kezaeiv/custom_weapons/ammo/ion.mdl
models/kezaeiv/custom_weapons/ammo/metal.mdl
models/kezaeiv/custom_weapons/ammo/nails.mdl
models/kezaeiv/custom_weapons/ammo/plasma.mdl
models/kezaeiv/custom_weapons/ammo/rockets.mdl
models/kezaeiv/custom_weapons/ammo/sniper.mdl
models/kezaeiv/custom_weapons/amr/p_amr.mdl
models/kezaeiv/custom_weapons/amr/v_amr.mdl
models/kezaeiv/custom_weapons/amr/w_amr.mdl
models/kezaeiv/custom_weapons/anvil/p_anvil.mdl
models/kezaeiv/custom_weapons/anvil/v_anvil.mdl
models/kezaeiv/custom_weapons/anvil/w_anvil.mdl
models/kezaeiv/custom_weapons/balista/p_balista.mdl
models/kezaeiv/custom_weapons/balista/titanium_bolt.mdl
models/kezaeiv/custom_weapons/balista/v_balista.mdl
models/kezaeiv/custom_weapons/balista/w_balista.mdl
models/kezaeiv/custom_weapons/commando/p_commando.mdl
models/kezaeiv/custom_weapons/commando/v_commando.mdl
models/kezaeiv/custom_weapons/commando/w_commando.mdl
models/kezaeiv/custom_weapons/de9/p_deagle_mk9.mdl
models/kezaeiv/custom_weapons/de9/v_deagle_mk9.mdl
models/kezaeiv/custom_weapons/de9/w_deagle_mk9.mdl
models/kezaeiv/custom_weapons/deic/p_destroyer.mdl
models/kezaeiv/custom_weapons/deic/v_destroyer.mdl
models/kezaeiv/custom_weapons/deic/w_destroyer.mdl
models/kezaeiv/custom_weapons/dev/p_devastator.mdl
models/kezaeiv/custom_weapons/dev/plasma_laser.mdl
models/kezaeiv/custom_weapons/dev/prism.mdl
models/kezaeiv/custom_weapons/dev/v_devastator.mdl
models/kezaeiv/custom_weapons/dev/w_devastator.mdl
models/kezaeiv/custom_weapons/dstinger/crimson_nail.mdl
models/kezaeiv/custom_weapons/dstinger/p_dstinger.mdl
models/kezaeiv/custom_weapons/dstinger/toxic_nail.mdl
models/kezaeiv/custom_weapons/dstinger/v_dstinger.mdl
models/kezaeiv/custom_weapons/dstinger/w_dstinger.mdl
models/kezaeiv/custom_weapons/ehve/p_ehve.mdl
models/kezaeiv/custom_weapons/ehve/v_ehve.mdl
models/kezaeiv/custom_weapons/ehve/w_ehve.mdl
models/kezaeiv/custom_weapons/factory/p_factory.mdl
models/kezaeiv/custom_weapons/factory/v_factory.mdl
models/kezaeiv/custom_weapons/factory/w_factory.mdl
models/kezaeiv/custom_weapons/freedom/p_freedom.mdl
models/kezaeiv/custom_weapons/freedom/v_freedom.mdl
models/kezaeiv/custom_weapons/freedom/w_freedom.mdl
models/kezaeiv/custom_weapons/frostbite/frost_nail.mdl
models/kezaeiv/custom_weapons/frostbite/p_frostbite.mdl
models/kezaeiv/custom_weapons/frostbite/v_frostbite.mdl
models/kezaeiv/custom_weapons/frostbite/w_frostbite.mdl
models/kezaeiv/custom_weapons/hyper_blaster/p_hblaster.mdl
models/kezaeiv/custom_weapons/hyper_blaster/v_hblaster.mdl
models/kezaeiv/custom_weapons/hyper_blaster/w_hblaster.mdl
models/kezaeiv/custom_weapons/mfg/p_mfg.mdl
models/kezaeiv/custom_weapons/mfg/v_mfg.mdl
models/kezaeiv/custom_weapons/mfg/w_mfg.mdl
models/kezaeiv/custom_weapons/mprl/p_mprl.mdl
models/kezaeiv/custom_weapons/mprl/v_mprl.mdl
models/kezaeiv/custom_weapons/mprl/w_mprl.mdl
models/kezaeiv/custom_weapons/obsidian/p_obsidian.mdl
models/kezaeiv/custom_weapons/obsidian/v_obsidian.mdl
models/kezaeiv/custom_weapons/obsidian/w_obsidian.mdl
models/kezaeiv/custom_weapons/partner/p_kez_partner.mdl
models/kezaeiv/custom_weapons/partner/v_kez_partner.mdl
models/kezaeiv/custom_weapons/partner/w_kez_partner.mdl
models/kezaeiv/custom_weapons/plasma_slayer/p_slayer.mdl
models/kezaeiv/custom_weapons/plasma_slayer/v_slayer.mdl
models/kezaeiv/custom_weapons/plasma_slayer/w_slayer.mdl
models/kezaeiv/custom_weapons/prodigy/p_prodigy.mdl
models/kezaeiv/custom_weapons/prodigy/prodigy_spore.mdl
models/kezaeiv/custom_weapons/prodigy/v_prodigy.mdl
models/kezaeiv/custom_weapons/prodigy/w_prodigy.mdl
models/kezaeiv/custom_weapons/purifier/p_purifier.mdl
models/kezaeiv/custom_weapons/purifier/v_purifier.mdl
models/kezaeiv/custom_weapons/purifier/w_purifier.mdl
models/kezaeiv/custom_weapons/raptor/p_raptor.mdl
models/kezaeiv/custom_weapons/raptor/v_raptor.mdl
models/kezaeiv/custom_weapons/raptor/w_raptor.mdl
models/kezaeiv/custom_weapons/seeker/p_seeker.mdl
models/kezaeiv/custom_weapons/seeker/v_seeker.mdl
models/kezaeiv/custom_weapons/seeker/w_seeker.mdl
models/kezaeiv/custom_weapons/shredder/p_shredder.mdl
models/kezaeiv/custom_weapons/shredder/v_shredder.mdl
models/kezaeiv/custom_weapons/shredder/w_shredder.mdl
models/kezaeiv/custom_weapons/surv/p_survivor.mdl
models/kezaeiv/custom_weapons/surv/v_survivor.mdl
models/kezaeiv/custom_weapons/surv/w_survivor.mdl
models/kezaeiv/custom_weapons/swarm/p_swarm.mdl
models/kezaeiv/custom_weapons/swarm/v_swarm.mdl
models/kezaeiv/custom_weapons/swarm/w_swarm.mdl
models/kezaeiv/kz_npcs/singularity/bullsquid_blue_ally.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_grey_marksman.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_grn_demoman.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_prpl_destroyer.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_red_leader.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_teal_raider.mdl
models/kezaeiv/kz_npcs/singularity/houndeye_green.mdl
models/kezaeiv/kz_npcs/singularity/houndeye_red.mdl
models/kezaeiv/kz_npcs/singularity/pit_blu_ally.mdl
models/kezaeiv/kz_npcs/singularity/pit_green_spiker.mdl
models/kezaeiv/kz_npcs/singularity/pit_prpl_slasher.mdl
models/kezaeiv/kz_npcs/singularity/pit_red_predator.mdl
models/kezaeiv/kz_npcs/singularity/robo_purple.mdl
models/kezaeiv/kz_npcs/singularity/strooper_grn_harvester.mdl
models/kezaeiv/kz_npcs/singularity/strooper_red_violent.mdl
models/kezaeiv/kz_npcs/singularity/strooper_vio_suppresor.mdl
sound/kezaeiv/c_wep/ammo/arrows.wav
sound/kezaeiv/c_wep/ammo/bullets.wav
sound/kezaeiv/c_wep/ammo/darkmatter.wav
sound/kezaeiv/c_wep/ammo/energy.wav
sound/kezaeiv/c_wep/ammo/grenades.wav
sound/kezaeiv/c_wep/ammo/health.wav
sound/kezaeiv/c_wep/ammo/metal.wav
sound/kezaeiv/c_wep/ammo/nails.wav
sound/kezaeiv/c_wep/ammo/pku_ammo1.wav
sound/kezaeiv/c_wep/ammo/pku_ammo2.wav
sound/kezaeiv/c_wep/ammo/pku_ammo3.wav
sound/kezaeiv/c_wep/ammo/pku_ammo4.wav
sound/kezaeiv/c_wep/ammo/plasma.wav
sound/kezaeiv/c_wep/ammo/rockets.wav
sound/kezaeiv/c_wep/ammo/shells.wav
sound/kezaeiv/c_wep/ammo/sniper.wav
sound/kezaeiv/c_wep/amr/igi_psgs1.wav
sound/kezaeiv/c_wep/amr/ss_snpr1.wav
sound/kezaeiv/c_wep/amr/ss_snpr2.wav
sound/kezaeiv/c_wep/amr/ss_snpr3.wav
sound/kezaeiv/c_wep/amr/wlf_stn1.wav
sound/kezaeiv/c_wep/anv/1shot.wav
sound/kezaeiv/c_wep/anv/2shots.wav
sound/kezaeiv/c_wep/anv/pump.wav
sound/kezaeiv/c_wep/anv/reload.wav
sound/kezaeiv/c_wep/com/cm_b1.wav
sound/kezaeiv/c_wep/com/cm_g1.wav
sound/kezaeiv/c_wep/com/cm_s1.wav
sound/kezaeiv/c_wep/com/cm_s2.wav
sound/kezaeiv/c_wep/de9/de_l1.wav
sound/kezaeiv/c_wep/de9/de_l2.wav
sound/kezaeiv/c_wep/de9/de_sh.wav
sound/kezaeiv/c_wep/destr/rail.wav
sound/kezaeiv/c_wep/dev/dev_crack.wav
sound/kezaeiv/c_wep/dev/dev_hit.wav
sound/kezaeiv/c_wep/dev/dev_meltdown.wav
sound/kezaeiv/c_wep/dev/dev_prism.wav
sound/kezaeiv/c_wep/dev/dev_rel2.wav
sound/kezaeiv/c_wep/dev/dev_rel3.wav
sound/kezaeiv/c_wep/dstngr/nail_hit_flesh.wav
sound/kezaeiv/c_wep/dstngr/nail_hit_wall.wav
sound/kezaeiv/c_wep/dstngr/spr_nail_hit.wav
sound/kezaeiv/c_wep/dstngr/sting01.wav
sound/kezaeiv/c_wep/dstngr/sting02.wav
sound/kezaeiv/c_wep/dstngr/sting03.wav
sound/kezaeiv/c_wep/dstngr/super_nail.wav
sound/kezaeiv/c_wep/dstngr/tox_hlth01.wav
sound/kezaeiv/c_wep/ehve/lightning.wav
sound/kezaeiv/c_wep/ehve/roach_blast.wav
sound/kezaeiv/c_wep/ehve/volt1.wav
sound/kezaeiv/c_wep/ehve/volt2.wav
sound/kezaeiv/c_wep/ehve/volt3.wav
sound/kezaeiv/c_wep/factr/fct_trnsfrmr.wav
sound/kezaeiv/c_wep/frdm/fire.wav
sound/kezaeiv/c_wep/frdm/rkt1.wav
sound/kezaeiv/c_wep/frdm/rotd.wav
sound/kezaeiv/c_wep/frdm/rotu.wav
sound/kezaeiv/c_wep/frst/ghst1.wav
sound/kezaeiv/c_wep/frst/silenced.wav
sound/kezaeiv/c_wep/frst/ss2_nade.wav
sound/kezaeiv/c_wep/hblst/hb_nova.wav
sound/kezaeiv/c_wep/hblst/hb_plsm.wav
sound/kezaeiv/c_wep/hblst/hb_plsm_blast.wav
sound/kezaeiv/c_wep/hblst/hb_plsm_chrg.wav
sound/kezaeiv/c_wep/hblst/hb_plsm_nova_fly01.wav
sound/kezaeiv/c_wep/hblst/hb_plsm_nova_fly02.wav
sound/kezaeiv/c_wep/knf/k_1.wav
sound/kezaeiv/c_wep/knf/k_2.wav
sound/kezaeiv/c_wep/knf/k_chrg.wav
sound/kezaeiv/c_wep/knf/k_slash1.wav
sound/kezaeiv/c_wep/knf/k_slash2.wav
sound/kezaeiv/c_wep/knf/k_thrw.wav
sound/kezaeiv/c_wep/mfg/grenade_fly.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce1.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce2.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce3.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce4.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce5.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit1.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit2.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit3.wav
sound/kezaeiv/c_wep/misc/change.wav
sound/kezaeiv/c_wep/misc/enrg_hit.wav
sound/kezaeiv/c_wep/misc/exp1.wav
sound/kezaeiv/c_wep/misc/exp2.wav
sound/kezaeiv/c_wep/misc/exp3.wav
sound/kezaeiv/c_wep/misc/implosion.wav
sound/kezaeiv/c_wep/misc/item_respawn.wav
sound/kezaeiv/c_wep/misc/noammo.wav
sound/kezaeiv/c_wep/misc/protect.wav
sound/kezaeiv/c_wep/misc/quad.wav
sound/kezaeiv/c_wep/misc/teleport.wav
sound/kezaeiv/c_wep/mprl/rkt_bounce.wav
sound/kezaeiv/c_wep/mprl/rkt_fly.wav
sound/kezaeiv/c_wep/mprl/rl_shoot.wav
sound/kezaeiv/c_wep/mprl/rl_shoot2.wav
sound/kezaeiv/c_wep/mprl/rl_shoot3.wav
sound/kezaeiv/c_wep/obs/burn1.wav
sound/kezaeiv/c_wep/obs/burn2.wav
sound/kezaeiv/c_wep/obs/flm1.wav
sound/kezaeiv/c_wep/obs/flm2.wav
sound/kezaeiv/c_wep/obs/plsm_nade.wav
sound/kezaeiv/c_wep/par/p_chrg.wav
sound/kezaeiv/c_wep/par/p_dest.wav
sound/kezaeiv/c_wep/par/p_dest_hit1.wav
sound/kezaeiv/c_wep/par/p_dest_hit2.wav
sound/kezaeiv/c_wep/par/p_dest_hit3.wav
sound/kezaeiv/c_wep/par/p_fire.wav
sound/kezaeiv/c_wep/par/p_rail.wav
sound/kezaeiv/c_wep/par/p_rail2.wav
sound/kezaeiv/c_wep/purifier/lg_fire_loop.wav
sound/kezaeiv/c_wep/purifier/lg_fire_start.wav
sound/kezaeiv/c_wep/purifier/lg_hit1.wav
sound/kezaeiv/c_wep/purifier/lg_hit2.wav
sound/kezaeiv/c_wep/purifier/lg_hit3.wav
sound/kezaeiv/c_wep/rptr/r_focus_shot.wav
sound/kezaeiv/c_wep/rptr/r_shot.wav
sound/kezaeiv/c_wep/rptr/r_sp.wav
sound/kezaeiv/c_wep/rptr/r_zoom.wav
sound/kezaeiv/c_wep/shrd/shrdr_1.wav
sound/kezaeiv/null.wav
sound/kezaeiv/sentences/commando/com_alreadythere.wav
sound/kezaeiv/sentences/commando/com_alright.wav
sound/kezaeiv/sentences/commando/com_alrightwhatyou.wav
sound/kezaeiv/sentences/commando/com_cya.wav
sound/kezaeiv/sentences/commando/com_cya2.wav
sound/kezaeiv/sentences/commando/com_ded1.wav
sound/kezaeiv/sentences/commando/com_ded10.wav
sound/kezaeiv/sentences/commando/com_ded4.wav
sound/kezaeiv/sentences/commando/com_ded5.wav
sound/kezaeiv/sentences/commando/com_ded8.wav
sound/kezaeiv/sentences/commando/com_ded9.wav
sound/kezaeiv/sentences/commando/com_dismissed.wav
sound/kezaeiv/sentences/commando/com_dontbeshy.wav
sound/kezaeiv/sentences/commando/com_fishinbarrel.wav
sound/kezaeiv/sentences/commando/com_forgetya.wav
sound/kezaeiv/sentences/commando/com_goodnight.wav
sound/kezaeiv/sentences/commando/com_gotapresentforya.wav
sound/kezaeiv/sentences/commando/com_gottabefun.wav
sound/kezaeiv/sentences/commando/com_gotyourpresent.wav
sound/kezaeiv/sentences/commando/com_hahaha.wav
sound/kezaeiv/sentences/commando/com_heartheplan.wav
sound/kezaeiv/sentences/commando/com_hesdone.wav
sound/kezaeiv/sentences/commando/com_igotthis.wav
sound/kezaeiv/sentences/commando/com_illputemdown.wav
sound/kezaeiv/sentences/commando/com_keepcoming.wav
sound/kezaeiv/sentences/commando/com_keepitdeja.wav
sound/kezaeiv/sentences/commando/com_knockemdown.wav
sound/kezaeiv/sentences/commando/com_later.wav
sound/kezaeiv/sentences/commando/com_lefthanded.wav
sound/kezaeiv/sentences/commando/com_leftstanding.wav
sound/kezaeiv/sentences/commando/com_loadnrock.wav
sound/kezaeiv/sentences/commando/com_maids.wav
sound/kezaeiv/sentences/commando/com_missedsomething.wav
sound/kezaeiv/sentences/commando/com_next.wav
sound/kezaeiv/sentences/commando/com_ohyeah.wav
sound/kezaeiv/sentences/commando/com_okboss.wav
sound/kezaeiv/sentences/commando/com_partystarted.wav
sound/kezaeiv/sentences/commando/com_roomservice.wav
sound/kezaeiv/sentences/commando/com_routine.wav
sound/kezaeiv/sentences/commando/com_runningstart.wav
sound/kezaeiv/sentences/commando/com_santacoming.wav
sound/kezaeiv/sentences/commando/com_seewhatyougot.wav
sound/kezaeiv/sentences/commando/com_sitdown.wav
sound/kezaeiv/sentences/commando/com_specialtreatment.wav
sound/kezaeiv/sentences/commando/com_surpriseunderthetree.wav
sound/kezaeiv/sentences/commando/com_sweet.wav
sound/kezaeiv/sentences/commando/com_takelong.wav
sound/kezaeiv/sentences/commando/com_targetpractice.wav
sound/kezaeiv/sentences/commando/com_tooez.wav
sound/kezaeiv/sentences/commando/com_toughtguy.wav
sound/kezaeiv/sentences/commando/com_whatyougot.wav
sound/kezaeiv/sentences/commando/com_wherearethey.wav
sound/kezaeiv/sentences/commando/com_yo.wav
sound/kezaeiv/sentences/marv/marv_assaultiniciated.wav
sound/kezaeiv/sentences/marv/marv_assaultvectoralpha.wav
sound/kezaeiv/sentences/marv/marv_bigguns.wav
sound/kezaeiv/sentences/marv/marv_crushthem.wav
sound/kezaeiv/sentences/marv/marv_deployingarmaments.wav
sound/kezaeiv/sentences/marv/marv_emmiterscharged.wav
sound/kezaeiv/sentences/marv/marv_fearless.wav
sound/kezaeiv/sentences/marv/marv_fullpower.wav
sound/kezaeiv/sentences/marv/marv_globaldefense.wav
sound/kezaeiv/sentences/marv/marv_heavyfire.wav
sound/kezaeiv/sentences/marv/marv_marv.wav
sound/kezaeiv/sentences/marv/marv_online.wav
sound/kezaeiv/sentences/marv/marv_onroute.wav
sound/kezaeiv/sentences/marv/marv_overwhelming.wav
sound/kezaeiv/sentences/marv/marv_pullingback.wav
sound/kezaeiv/sentences/marv/marv_readytodeploy.wav
sound/kezaeiv/sentences/marv/marv_readytoroll.wav
sound/kezaeiv/sentences/marv/marv_readytoroll2.wav
sound/kezaeiv/sentences/marv/marv_reclamationinprogress2.wav
sound/kezaeiv/sentences/marv/marv_reclamationops.wav
sound/kezaeiv/sentences/marv/marv_refactoring.wav
sound/kezaeiv/sentences/marv/marv_retreating.wav
sound/kezaeiv/sentences/marv/marv_revisingdeployment.wav
sound/kezaeiv/sentences/marv/marv_revisingdeployment2.wav
sound/kezaeiv/sentences/marv/marv_sizematters.wav
sound/kezaeiv/sentences/marv/marv_systemsengaged.wav
sound/kezaeiv/sentences/marv/marv_systemsonline.wav
sound/kezaeiv/sentences/marv/marv_takebacktheplanet.wav
sound/kezaeiv/sentences/marv/marv_theearthwill.wav
sound/kezaeiv/sentences/marv/marv_tiberium.wav
sound/kezaeiv/sentences/marv/marv_watchingmy6.wav
sound/kezaeiv/sentences/marv/marv_what.wav
sound/kezaeiv/sentences/zonetrooper/zt_aliveandready.wav
sound/kezaeiv/sentences/zonetrooper/zt_die1.wav
sound/kezaeiv/sentences/zonetrooper/zt_die10.wav
sound/kezaeiv/sentences/zonetrooper/zt_die2.wav
sound/kezaeiv/sentences/zonetrooper/zt_die3.wav
sound/kezaeiv/sentences/zonetrooper/zt_die4.wav
sound/kezaeiv/sentences/zonetrooper/zt_die7.wav
sound/kezaeiv/sentences/zonetrooper/zt_die8.wav
sound/kezaeiv/sentences/zonetrooper/zt_getgotthis.wav
sound/kezaeiv/sentences/zonetrooper/zt_goingin.wav
sound/kezaeiv/sentences/zonetrooper/zt_gotaload.wav
sound/kezaeiv/sentences/zonetrooper/zt_gotem.wav
sound/kezaeiv/sentences/zonetrooper/zt_gotit.wav
sound/kezaeiv/sentences/zonetrooper/zt_haveatit.wav
sound/kezaeiv/sentences/zonetrooper/zt_havesomeofthis.wav
sound/kezaeiv/sentences/zonetrooper/zt_hitit.wav
sound/kezaeiv/sentences/zonetrooper/zt_illcheckit.wav
sound/kezaeiv/sentences/zonetrooper/zt_keepem.wav
sound/kezaeiv/sentences/zonetrooper/zt_letsdoit.wav
sound/kezaeiv/sentences/zonetrooper/zt_letsgetover.wav
sound/kezaeiv/sentences/zonetrooper/zt_letsgo.wav
sound/kezaeiv/sentences/zonetrooper/zt_letsgo2.wav
sound/kezaeiv/sentences/zonetrooper/zt_letsmove.wav
sound/kezaeiv/sentences/zonetrooper/zt_mhmm.wav
sound/kezaeiv/sentences/zonetrooper/zt_movein.wav
sound/kezaeiv/sentences/zonetrooper/zt_ohyeah.wav
sound/kezaeiv/sentences/zonetrooper/zt_overez.wav
sound/kezaeiv/sentences/zonetrooper/zt_pinemdown.wav
sound/kezaeiv/sentences/zonetrooper/zt_punchit.wav
sound/kezaeiv/sentences/zonetrooper/zt_readyforaction.wav
sound/kezaeiv/sentences/zonetrooper/zt_shutthisparty.wav
sound/kezaeiv/sentences/zonetrooper/zt_sittight.wav
sound/kezaeiv/sentences/zonetrooper/zt_takeem.wav
sound/kezaeiv/sentences/zonetrooper/zt_thatsright.wav
sound/kezaeiv/sentences/zonetrooper/zt_timetogo.wav
sound/kezaeiv/sentences/zonetrooper/zt_troopersinthefield.wav
sound/kezaeiv/sentences/zonetrooper/zt_troopersquad.wav
sound/kezaeiv/sentences/zonetrooper/zt_undercontrol.wav
sound/kezaeiv/sentences/zonetrooper/zt_wantmore.wav
sound/kezaeiv/sentences/zonetrooper/zt_wearehere.wav
sound/kezaeiv/sentences/zonetrooper/zt_weareout.wav
sound/kezaeiv/sentences/zonetrooper/zt_wegotthisone.wav
sound/kezaeiv/sentences/zonetrooper/zt_wehearya.wav
sound/kezaeiv/sentences/zonetrooper/zt_whatsthecall.wav
sound/kezaeiv/sentences/zonetrooper/zt_whatyouneed.wav
sound/kezaeiv/sentences/zonetrooper/zt_youknow.wav
sound/kezaeiv/singularity/npc/dusk_shotgun_shot.wav
sound/kezaeiv/singularity/npc/hgrunt_3shot.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit1.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit2.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit3.wav
sound/kezaeiv/singularity/npc/igi2_dragunov_shot.wav
sound/kezaeiv/singularity/npc/igi2_g36_shot.wav
sound/kezaeiv/singularity/npc/quake3_grenade_shot.wav
sound/kezaeiv/singularity/npc/quake4_plasma_shot.wav
sound/kezaeiv/singularity/npc/starcraft_ghost_rifle.wav
sound/kezaeiv/singularity/player/death.wav
sound/squeek/sqk_startled.wav
sound/squeek/sqk_strugglefit1.wav
sound/squeek/sqk_strugglefit2.wav
sound/squeek/sqk_strugglefit3.wav
sound/squeek/sqk_strugglenip1.wav
sound/squeek/sqk_strugglenip2.wav
sound/weapons/357_close.wav
sound/weapons/357_hammerpull.wav
sound/weapons/357_open.wav
sound/weapons/357_reload.wav
sound/weapons/357_shellin.wav
sound/weapons/357_shellsdrop.wav
sound/weapons/alien_draw.wav
sound/weapons/alien_holster.wav
sound/weapons/alien_shake.wav
sound/weapons/alien_sway.wav
sound/weapons/crossbow_bolt.wav
sound/weapons/crossbow_draw.wav
sound/weapons/crossbow_fidget.wav
sound/weapons/crossbow_maghold.wav
sound/weapons/crossbow_magin.wav
sound/weapons/crossbow_magout.wav
sound/weapons/crossbow_magready.wav
sound/weapons/crossbow_pull.wav
sound/weapons/deagle_clipin.wav
sound/weapons/deagle_clipout.wav
sound/weapons/deagle_movement.wav
sound/weapons/deagle_slide.wav
sound/weapons/deagle_slideback.wav
sound/weapons/deagle_sliderelease.wav
sound/weapons/egon_handle1.wav
sound/weapons/egon_handle2.wav
sound/weapons/fidget_2.wav
sound/weapons/fidget_3.wav
sound/weapons/fidget_4.wav
sound/weapons/fidget_6.wav
sound/weapons/gauss_fidget.wav
sound/weapons/glock_clipin.wav
sound/weapons/glock_clipout.wav
sound/weapons/glock_empty.wav
sound/weapons/glock_slideback.wav
sound/weapons/glock_slideforward.wav
sound/weapons/glock_sliderelease.wav
sound/weapons/grenade_pinpull.wav
sound/weapons/grenade_throw.wav
sound/weapons/hks_clic1.wav
sound/weapons/m40a1_clipin.wav
sound/weapons/m40a1_clipout.wav
sound/weapons/m40a1_cliptap.wav
sound/weapons/m41a_load.wav
sound/weapons/M4_boltpull.wav
sound/weapons/M4_clipin.wav
sound/weapons/M4_clipmiddle.wav
sound/weapons/M4_clipout.wav
sound/weapons/M4_cliptap.wav
sound/weapons/MP5_clipinsert1.wav
sound/weapons/MP5_cliprelease1.wav
sound/weapons/mp5_grenadelauncher_1.wav
sound/weapons/mp5_grenadelauncher_2.wav
sound/weapons/mp5_m203_grenade_insert.wav
sound/weapons/reload_done.wav
sound/weapons/RPG_fidget.wav
sound/weapons/rpg_getrocket.wav
sound/weapons/rpg_load.wav
sound/weapons/scock_back.wav
sound/weapons/scock_forward.wav
sound/weapons/spas12_foley.wav
sound/weapons/spas_idle4.wav
sound/weapons/splauncher_draw.wav
sound/weapons/splauncher_idle.wav
sound/weapons/start_reload.wav
sound/weapons/uzi_akimbo_pull1.wav
sound/weapons/uzi_akimbo_pull2.wav
sound/weapons/uzi_boltback.wav
sound/weapons/uzi_clip_connect.wav
sound/weapons/uzi_deploy1.wav
sound/weapons/uzi_reload1.wav
sound/weapons/uzi_reload2.wav
sound/weapons/uzi_reload_left1.wav
sound/weapons/uzi_reload_left2.wav
sound/weapons/uzi_reload_right1.wav
sound/weapons/uzi_reload_right2.wav
sound/weapons/weapon_catch.wav
sound/weapons/weapon_draw.wav
sound/weapons/weapon_holster.wav
sprites/640tfcminigun.spr
sprites/kezaeiv/c_wep/weapon_amr.txt
sprites/kezaeiv/c_wep/weapon_anvil.txt
sprites/kezaeiv/c_wep/weapon_balista.txt
sprites/kezaeiv/c_wep/weapon_commando.txt
sprites/kezaeiv/c_wep/weapon_deagle_mk9.txt
sprites/kezaeiv/c_wep/weapon_destroyer.txt
sprites/kezaeiv/c_wep/weapon_devastator.txt
sprites/kezaeiv/c_wep/weapon_duality_stinger.txt
sprites/kezaeiv/c_wep/weapon_ehve.txt
sprites/kezaeiv/c_wep/weapon_factory.txt
sprites/kezaeiv/c_wep/weapon_freedom_machine.txt
sprites/kezaeiv/c_wep/weapon_frostbite.txt
sprites/kezaeiv/c_wep/weapon_hyper_blaster.txt
sprites/kezaeiv/c_wep/weapon_kez_partner.txt
sprites/kezaeiv/c_wep/weapon_modified_frag_grenade.txt
sprites/kezaeiv/c_wep/weapon_mprl.txt
sprites/kezaeiv/c_wep/weapon_obsidian.txt
sprites/kezaeiv/c_wep/weapon_plasma_slayer.txt
sprites/kezaeiv/c_wep/weapon_prodigy_launcher.txt
sprites/kezaeiv/c_wep/weapon_purifier.txt
sprites/kezaeiv/c_wep/weapon_raptor_sniper.txt
sprites/kezaeiv/c_wep/weapon_seeker.txt
sprites/kezaeiv/c_wep/weapon_shredder.txt
sprites/kezaeiv/c_wep/weapon_survivor.txt
sprites/kezaeiv/c_wep/weapon_swarm.txt
sprites/kezaeiv/fx/hotglow_crimson.spr
sprites/kezaeiv/fx/hotglow_cyan.spr
sprites/kezaeiv/fx/hotglow_prpl.spr
sprites/kezaeiv/fx/laser_crshr.spr
sprites/kezaeiv/fx/laser_crshr_cy.spr
sprites/kezaeiv/fx/laser_crshr_grn.spr
sprites/kezaeiv/fx/laser_crshr_wht.spr
sprites/kezaeiv/kezammo.spr
sprites/kezaeiv/kezcrosshairs.spr
sprites/kezaeiv/kezsniper.spr
sprites/kezaeiv/xpl/hexplo_crmsn.spr
sprites/kezaeiv/xpl/zxlp_blue.spr
sprites/kezaeiv/xpl/zxlp_crimson.spr
sprites/kezaeiv/xpl/zxlp_lila.spr
sprites/kezaeiv/xpl/zxlp_purple.spr
sprites/m41a_off.spr
sprites/m41a_on.spr
sprites/tfchud01.spr
sprites/tfchud02.spr
sprites/weapon_knife.spr
