// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

asheep.wad
models/azuresheep/barniel.mdl
models/azuresheep/kate.mdl
models/kezaeiv/icons/mk_logo_blue.mdl
models/kezaeiv/icons/mk_logo_orange.mdl
models/oghs/barney/v_357.mdl
models/oghs/barney/v_9mmar.mdl
models/oghs/barney/v_crossbow.mdl
models/oghs/barney/v_crowbar.mdl
models/oghs/barney/v_desert_eagle.mdl
models/oghs/barney/v_displacer.mdl
models/oghs/barney/v_egon.mdl
models/oghs/barney/v_gauss.mdl
models/oghs/barney/v_glock.mdl
models/oghs/barney/v_grenade.mdl
models/oghs/barney/v_m16a2.mdl
models/oghs/barney/v_m40a1.mdl
models/oghs/barney/v_medkit.mdl
models/oghs/barney/v_pipe_wrench.mdl
models/oghs/barney/v_poolstick.mdl
models/oghs/barney/v_rpg.mdl
models/oghs/barney/v_satchel.mdl
models/oghs/barney/v_satchel_radio.mdl
models/oghs/barney/v_saw.mdl
models/oghs/barney/v_shotgun.mdl
models/oghs/barney/v_spore_launcher.mdl
models/oghs/barney/v_squeak.mdl
models/oghs/barney/v_tripmine.mdl
models/oghs/barney/v_uzi.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn.mdl
models/oghs/cm/npc/massnf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/Tor.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_minigunidle.mdl
models/oghs/cm/wep/p_minigunspin.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_minigun.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
sound/azuresheep/_comma.wav
sound/azuresheep/ambience/computalk3.wav
sound/azuresheep/barney/goon.wav
sound/azuresheep/barniel/_comma.wav
sound/azuresheep/barniel/aimforhead.wav
sound/azuresheep/barniel/badfeeling.wav
sound/azuresheep/barniel/bequiet.wav
sound/azuresheep/barniel/bn_another.wav
sound/azuresheep/barniel/bn_attack1.wav
sound/azuresheep/barniel/bn_becarefull.wav
sound/azuresheep/barniel/bn_bring.wav
sound/azuresheep/barniel/bn_carefull.wav
sound/azuresheep/barniel/bn_close.wav
sound/azuresheep/barniel/bn_die1.wav
sound/azuresheep/barniel/bn_dontdothat.wav
sound/azuresheep/barniel/bn_dontmake.wav
sound/azuresheep/barniel/bn_endline.wav
sound/azuresheep/barniel/bn_firepl.wav
sound/azuresheep/barniel/bn_friends.wav
sound/azuresheep/barniel/bn_gotone.wav
sound/azuresheep/barniel/bn_iwish.wav
sound/azuresheep/barniel/bn_onelessh.wav
sound/azuresheep/barniel/bn_pain1.wav
sound/azuresheep/barniel/bn_pain2.wav
sound/azuresheep/barniel/bn_post.wav
sound/azuresheep/barniel/bn_seethat.wav
sound/azuresheep/barniel/bn_somuch.wav
sound/azuresheep/barniel/bn_stepoff.wav
sound/azuresheep/barniel/bn_tomb.wav
sound/azuresheep/barniel/bn_uwish.wav
sound/azuresheep/barniel/bn_whatyou.wav
sound/azuresheep/barniel/diegreenthing.wav
sound/azuresheep/barniel/dontagree.wav
sound/azuresheep/barniel/dontknow.wav
sound/azuresheep/barniel/drinktopside.wav
sound/azuresheep/barniel/hearsomething.wav
sound/azuresheep/barniel/hevno.wav
sound/azuresheep/barniel/hi.wav
sound/azuresheep/barniel/hitbad.wav
sound/azuresheep/barniel/humm.wav
sound/azuresheep/barniel/imhit.wav
sound/azuresheep/barniel/movietv.wav
sound/azuresheep/barniel/nosir.wav
sound/azuresheep/barniel/openfire.wav
sound/azuresheep/barniel/rightway.wav
sound/azuresheep/barniel/seelater.wav
sound/azuresheep/barniel/seeya.wav
sound/azuresheep/barniel/slimything.wav
sound/azuresheep/barniel/somethingmoves.wav
sound/azuresheep/barniel/stop1.wav
sound/azuresheep/barniel/teamup1.wav
sound/azuresheep/barniel/teamup2.wav
sound/azuresheep/barniel/thinking.wav
sound/azuresheep/barniel/waitin.wav
sound/azuresheep/barniel/whatsgoingon.wav
sound/azuresheep/barniel/yessir.wav
sound/azuresheep/barniel/youneedmedic.wav
sound/azuresheep/gordon/aimforhead.wav
sound/azuresheep/gordon/aintscared.wav
sound/azuresheep/gordon/ambush.wav
sound/azuresheep/gordon/bigmess.wav
sound/azuresheep/gordon/checkwounds.wav
sound/azuresheep/gordon/diebloodsucker.wav
sound/azuresheep/gordon/dobettertogether.wav
sound/azuresheep/gordon/dontbet.wav
sound/azuresheep/gordon/donthurtem.wav
sound/azuresheep/gordon/getanyworse.wav
sound/azuresheep/gordon/gladof38.wav
sound/azuresheep/gordon/gladtolendhand.wav
sound/azuresheep/gordon/go_another.wav
sound/azuresheep/gordon/go_bring.wav
sound/azuresheep/gordon/go_buttugly.wav
sound/azuresheep/gordon/go_close.wav
sound/azuresheep/gordon/go_dontmake.wav
sound/azuresheep/gordon/go_dotoyou.wav
sound/azuresheep/gordon/go_endline.wav
sound/azuresheep/gordon/go_firepl.wav
sound/azuresheep/gordon/go_friends.wav
sound/azuresheep/gordon/go_gotone.wav
sound/azuresheep/gordon/go_iwish.wav
sound/azuresheep/gordon/go_pain2.wav
sound/azuresheep/gordon/go_seethat.wav
sound/azuresheep/gordon/go_somuch.wav
sound/azuresheep/gordon/go_stepoff.wav
sound/azuresheep/gordon/go_tomb.wav
sound/azuresheep/gordon/go_uwish.wav
sound/azuresheep/gordon/go_watchit.wav
sound/azuresheep/gordon/go_whatyou.wav
sound/azuresheep/gordon/go_whoathere.wav
sound/azuresheep/gordon/hearsomething.wav
sound/azuresheep/gordon/hearsomething2.wav
sound/azuresheep/gordon/hellonicesuit.wav
sound/azuresheep/gordon/hitbad.wav
sound/azuresheep/gordon/imdead.wav
sound/azuresheep/gordon/imhit.wav
sound/azuresheep/gordon/leavealone.wav
sound/azuresheep/gordon/luckwillturn.wav
sound/azuresheep/gordon/noway.wav
sound/azuresheep/gordon/seeya.wav
sound/azuresheep/gordon/slowingyoudown.wav
sound/azuresheep/gordon/somethingdied.wav
sound/azuresheep/gordon/somethingmoves.wav
sound/azuresheep/gordon/soundsright.wav
sound/azuresheep/gordon/standback.wav
sound/azuresheep/gordon/standguard.wav
sound/azuresheep/gordon/stench.wav
sound/azuresheep/gordon/stop1.wav
sound/azuresheep/gordon/stop2.wav
sound/azuresheep/gordon/targetpractice.wav
sound/azuresheep/gordon/teamup1.wav
sound/azuresheep/gordon/yougotit.wav
sound/azuresheep/gordon/youhearthat.wav
sound/azuresheep/gordon/youneedmedic.wav
sound/azuresheep/gordon/yup.wav
sound/azuresheep/kate/aimforhead.wav
sound/azuresheep/kate/anotherdown.wav
sound/azuresheep/kate/badfelling.wav
sound/azuresheep/kate/becarefull.wav
sound/azuresheep/kate/bequiet.wav
sound/azuresheep/kate/bigeye.wav
sound/azuresheep/kate/bringitone.wav
sound/azuresheep/kate/close.wav
sound/azuresheep/kate/correctway.wav
sound/azuresheep/kate/cupoftie.wav
sound/azuresheep/kate/didntwantthis.wav
sound/azuresheep/kate/didseeshot.wav
sound/azuresheep/kate/dieslimy.wav
sound/azuresheep/kate/dinnerend.wav
sound/azuresheep/kate/dontagree.wav
sound/azuresheep/kate/dontdothat.wav
sound/azuresheep/kate/dontdothis.wav
sound/azuresheep/kate/dontknow.wav
sound/azuresheep/kate/dontwantlive.wav
sound/azuresheep/kate/freebarney.wav
sound/azuresheep/kate/friendslikeyou.wav
sound/azuresheep/kate/gotanother.wav
sound/azuresheep/kate/gotone.wav
sound/azuresheep/kate/hearsomething.wav
sound/azuresheep/kate/hevno.wav
sound/azuresheep/kate/hi.wav
sound/azuresheep/kate/hitbad.wav
sound/azuresheep/kate/hitbad2.wav
sound/azuresheep/kate/hoyes.wav
sound/azuresheep/kate/hummm.wav
sound/azuresheep/kate/iamkate.wav
sound/azuresheep/kate/ka_attack1.wav
sound/azuresheep/kate/muchmore.wav
sound/azuresheep/kate/notatall.wav
sound/azuresheep/kate/oneless.wav
sound/azuresheep/kate/openfire.wav
sound/azuresheep/kate/resquedatlast.wav
sound/azuresheep/kate/seelater.wav
sound/azuresheep/kate/seeyoulater.wav
sound/azuresheep/kate/somethingmove.wav
sound/azuresheep/kate/staypost.wav
sound/azuresheep/kate/stepoff.wav
sound/azuresheep/kate/stop1.wav
sound/azuresheep/kate/teamup1.wav
sound/azuresheep/kate/teamup2.wav
sound/azuresheep/kate/thinking.wav
sound/azuresheep/kate/waithere.wav
sound/azuresheep/kate/waithere2.wav
sound/azuresheep/kate/welcome.wav
sound/azuresheep/kate/whatgoingon.wav
sound/azuresheep/kate/whatyoudoing.wav
sound/azuresheep/kate/yesbarn.wav
sound/azuresheep/kate/youaredead.wav
sound/azuresheep/kate/youneedmedic.wav
sound/azuresheep/kate/youwish.wav
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/scientist/noopen.wav
sound/scientist/sci_alone2.wav
sound/scientist/wareh.wav
sound/weapons/desert_eagle_clipin.wav
sound/weapons/desert_eagle_clipout.wav
sound/weapons/sniper_reload1.wav
sound/weapons/sniper_reload2.wav
sound/weapons/sniper_reload4_bolt.wav
