// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/Embassybk.tga
gfx/env/Embassydn.tga
gfx/env/Embassyft.tga
gfx/env/Embassylf.tga
gfx/env/Embassyrt.tga
gfx/env/Embassyup.tga
models/con3/tree35.mdl
models/kezaeiv/clssc/wps/p_2uzis.mdl
models/kezaeiv/clssc/wps/p_2uzis_gold.mdl
models/kezaeiv/clssc/wps/p_displacer.mdl
models/kezaeiv/clssc/wps/p_gauss.mdl
models/kezaeiv/clssc/wps/p_minigunidle.mdl
models/kezaeiv/clssc/wps/p_minigunspin.mdl
models/kezaeiv/clssc/wps/p_shock.mdl
models/kezaeiv/clssc/wps/p_spore_launcher.mdl
models/kezaeiv/clssc/wps/p_uzi.mdl
models/kezaeiv/clssc/wps/p_uzi_gold.mdl
models/kezaeiv/clssc/wps/v_9mmar.mdl
models/kezaeiv/clssc/wps/v_bgrap.mdl
models/kezaeiv/clssc/wps/v_crowbar.mdl
models/kezaeiv/clssc/wps/v_desert_eagle.mdl
models/kezaeiv/clssc/wps/v_displacer.mdl
models/kezaeiv/clssc/wps/v_egon.mdl
models/kezaeiv/clssc/wps/v_gauss2.mdl
models/kezaeiv/clssc/wps/v_grenade.mdl
models/kezaeiv/clssc/wps/v_medkit.mdl
models/kezaeiv/clssc/wps/v_minigun.mdl
models/kezaeiv/clssc/wps/v_pipe_wrench.mdl
models/kezaeiv/clssc/wps/v_satchel.mdl
models/kezaeiv/clssc/wps/v_shock.mdl
models/kezaeiv/clssc/wps/v_shotgun.mdl
models/kezaeiv/clssc/wps/v_spore_launcher.mdl
models/kezaeiv/clssc/wps/v_squeak.mdl
models/kezaeiv/clssc/wps/v_tripmine.mdl
models/kezaeiv/clssc/wps/v_uzi.mdl
models/kezaeiv/clssc/wps/w_2uzis.mdl
models/kezaeiv/clssc/wps/w_2uzis_gold.mdl
models/kezaeiv/clssc/wps/w_displacer.mdl
models/kezaeiv/clssc/wps/w_gauss.mdl
models/kezaeiv/clssc/wps/w_minigun.mdl
models/kezaeiv/clssc/wps/w_shock.mdl
models/kezaeiv/clssc/wps/w_shock_rifle.mdl
models/kezaeiv/clssc/wps/w_spore_launcher.mdl
models/kezaeiv/clssc/wps/w_uzi.mdl
models/kezaeiv/clssc/wps/w_uzi_clip.mdl
models/kezaeiv/clssc/wps/w_uzi_gold.mdl
models/kezaeiv/custom_weapons/ammo/amrclip.mdl
models/kezaeiv/custom_weapons/ammo/nails.mdl
models/kezaeiv/custom_weapons/ammo/plasma.mdl
models/kezaeiv/custom_weapons/ammo/quad_nail.mdl
models/kezaeiv/custom_weapons/ammo/rockets.mdl
models/kezaeiv/custom_weapons/ammo/sniper.mdl
models/kezaeiv/custom_weapons/ammo/uranium_arrows.mdl
models/kezaeiv/custom_weapons/amr/p_amr.mdl
models/kezaeiv/custom_weapons/amr/v_amr.mdl
models/kezaeiv/custom_weapons/amr/w_amr.mdl
models/kezaeiv/custom_weapons/balista/p_balista.mdl
models/kezaeiv/custom_weapons/balista/titanium_bolt.mdl
models/kezaeiv/custom_weapons/balista/v_balista.mdl
models/kezaeiv/custom_weapons/balista/w_balista.mdl
models/kezaeiv/custom_weapons/commando/p_commando.mdl
models/kezaeiv/custom_weapons/commando/v_commando.mdl
models/kezaeiv/custom_weapons/commando/w_commando.mdl
models/kezaeiv/custom_weapons/dev/p_devastator.mdl
models/kezaeiv/custom_weapons/dev/prism.mdl
models/kezaeiv/custom_weapons/dev/v_devastator.mdl
models/kezaeiv/custom_weapons/dev/w_devastator.mdl
models/kezaeiv/custom_weapons/dstinger/crimson_nail.mdl
models/kezaeiv/custom_weapons/dstinger/p_dstinger.mdl
models/kezaeiv/custom_weapons/dstinger/toxic_nail.mdl
models/kezaeiv/custom_weapons/dstinger/v_dstinger.mdl
models/kezaeiv/custom_weapons/dstinger/w_dstinger.mdl
models/kezaeiv/custom_weapons/freedom/cannonball.mdl
models/kezaeiv/custom_weapons/freedom/p_freedom.mdl
models/kezaeiv/custom_weapons/freedom/v_freedom.mdl
models/kezaeiv/custom_weapons/freedom/w_freedom.mdl
models/kezaeiv/custom_weapons/frostbite/frost_nail.mdl
models/kezaeiv/custom_weapons/frostbite/p_frostbite.mdl
models/kezaeiv/custom_weapons/frostbite/v_frostbite.mdl
models/kezaeiv/custom_weapons/frostbite/w_frostbite.mdl
models/kezaeiv/custom_weapons/mprl/p_mprl.mdl
models/kezaeiv/custom_weapons/mprl/v_mprl.mdl
models/kezaeiv/custom_weapons/mprl/w_mprl.mdl
models/kezaeiv/custom_weapons/obsidian/p_obsidian.mdl
models/kezaeiv/custom_weapons/obsidian/v_obsidian.mdl
models/kezaeiv/custom_weapons/obsidian/w_obsidian.mdl
models/kezaeiv/custom_weapons/partner/p_kez_partner.mdl
models/kezaeiv/custom_weapons/partner/v_kez_partner.mdl
models/kezaeiv/custom_weapons/partner/w_kez_partner.mdl
models/kezaeiv/custom_weapons/plasma_slayer/p_slayer.mdl
models/kezaeiv/custom_weapons/plasma_slayer/v_slayer.mdl
models/kezaeiv/custom_weapons/plasma_slayer/w_slayer.mdl
models/kezaeiv/custom_weapons/prodigy/prodigy_plant.mdl
models/kezaeiv/custom_weapons/prodigy/prodigy_spore.mdl
models/kezaeiv/custom_weapons/raptor/p_raptor.mdl
models/kezaeiv/custom_weapons/raptor/v_raptor.mdl
models/kezaeiv/custom_weapons/raptor/w_raptor.mdl
models/kezaeiv/custom_weapons/seeker/p_seeker.mdl
models/kezaeiv/custom_weapons/seeker/v_seeker.mdl
models/kezaeiv/custom_weapons/seeker/w_seeker.mdl
models/kezaeiv/icons/mk_logo_crimson.mdl
models/kezaeiv/icons/pu/mk_logo_blue.mdl
models/kezaeiv/icons/pu/mk_logo_cyan.mdl
models/kezaeiv/icons/pu/mk_logo_purple.mdl
models/kezaeiv/icons/pu/mk_logo_transparent.mdl
models/kezaeiv/kz_npcs/singularity/agrunt.mdl
models/kezaeiv/kz_npcs/singularity/agruntf.mdl
models/kezaeiv/kz_npcs/singularity/apache.mdl
models/kezaeiv/kz_npcs/singularity/apachef.mdl
models/kezaeiv/kz_npcs/singularity/baby_voltigore.mdl
models/kezaeiv/kz_npcs/singularity/babygarg.mdl
models/kezaeiv/kz_npcs/singularity/babygargf.mdl
models/kezaeiv/kz_npcs/singularity/barnabushev.mdl
models/kezaeiv/kz_npcs/singularity/barneyhev.mdl
models/kezaeiv/kz_npcs/singularity/bgman.mdl
models/kezaeiv/kz_npcs/singularity/bullsquid.mdl
models/kezaeiv/kz_npcs/singularity/chubby.mdl
models/kezaeiv/kz_npcs/singularity/chumtoad.mdl
models/kezaeiv/kz_npcs/singularity/controller_master.mdl
models/kezaeiv/kz_npcs/singularity/gonome.mdl
models/kezaeiv/kz_npcs/singularity/hassassin.mdl
models/kezaeiv/kz_npcs/singularity/hassassinf.mdl
models/kezaeiv/kz_npcs/singularity/headcrab.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_medicf.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_opforf.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_red_leader.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_torchf.mdl
models/kezaeiv/kz_npcs/singularity/hgrunt_yllw_mp5b.mdl
models/kezaeiv/kz_npcs/singularity/hgruntf.mdl
models/kezaeiv/kz_npcs/singularity/houndeye_green.mdl
models/kezaeiv/kz_npcs/singularity/houndeye_red.mdl
models/kezaeiv/kz_npcs/singularity/hwgrunt.mdl
models/kezaeiv/kz_npcs/singularity/hwgruntf.mdl
models/kezaeiv/kz_npcs/singularity/islave.mdl
models/kezaeiv/kz_npcs/singularity/islavef.mdl
models/kezaeiv/kz_npcs/singularity/kingpin.mdl
models/kezaeiv/kz_npcs/singularity/mass_tactical.mdl
models/kezaeiv/kz_npcs/singularity/massn_ghost.mdl
models/kezaeiv/kz_npcs/singularity/massnf.mdl
models/kezaeiv/kz_npcs/singularity/massnf_kez.mdl
models/kezaeiv/kz_npcs/singularity/osprey.mdl
models/kezaeiv/kz_npcs/singularity/ospreyf.mdl
models/kezaeiv/kz_npcs/singularity/pit_red_predator.mdl
models/kezaeiv/kz_npcs/singularity/robo_grunt.mdl
models/kezaeiv/kz_npcs/singularity/robo_purple.mdl
models/kezaeiv/kz_npcs/singularity/robo_red_leader.mdl
models/kezaeiv/kz_npcs/singularity/sentry_red.mdl
models/kezaeiv/kz_npcs/singularity/strooper_blu_prodigy.mdl
models/kezaeiv/kz_npcs/singularity/strooper_red_violent.mdl
models/kezaeiv/kz_npcs/singularity/strooper_vio_suppresor.mdl
models/kezaeiv/kz_npcs/singularity/tor.mdl
models/kezaeiv/kz_npcs/singularity/torf.mdl
models/kezaeiv/kz_npcs/singularity/voltigore.mdl
models/kezaeiv/kz_npcs/singularity/zombie.mdl
models/kezaeiv/kz_npcs/singularity/zombie_barney.mdl
models/kezaeiv/kz_npcs/singularity/zombie_soldier.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
sound/con3/bloodytom.wav
sound/con3/cargo_door.wav
sound/con3/fragments.wav
sound/kezaeiv/c_wep/ammo/energy.wav
sound/kezaeiv/c_wep/ammo/nails.wav
sound/kezaeiv/c_wep/ammo/pku_ammo1.wav
sound/kezaeiv/c_wep/ammo/pku_ammo3.wav
sound/kezaeiv/c_wep/ammo/pku_ammo5.wav
sound/kezaeiv/c_wep/ammo/plasma.wav
sound/kezaeiv/c_wep/ammo/quadnail.wav
sound/kezaeiv/c_wep/ammo/rockets.wav
sound/kezaeiv/c_wep/ammo/sniper.wav
sound/kezaeiv/c_wep/amr/igi_psgs1.wav
sound/kezaeiv/c_wep/amr/ss_snpr1.wav
sound/kezaeiv/c_wep/amr/ss_snpr2.wav
sound/kezaeiv/c_wep/amr/ss_snpr3.wav
sound/kezaeiv/c_wep/amr/wlf_stn1.wav
sound/kezaeiv/c_wep/bal/bal_sht3.wav
sound/kezaeiv/c_wep/bal/f_hit1.wav
sound/kezaeiv/c_wep/bal/f_hit2.wav
sound/kezaeiv/c_wep/com/cm_b1.wav
sound/kezaeiv/c_wep/com/cm_g1.wav
sound/kezaeiv/c_wep/com/cm_s1.wav
sound/kezaeiv/c_wep/de9/de_sh.wav
sound/kezaeiv/c_wep/dev/dev_crack.wav
sound/kezaeiv/c_wep/dev/dev_hit.wav
sound/kezaeiv/c_wep/dev/dev_meltdown.wav
sound/kezaeiv/c_wep/dev/dev_prism.wav
sound/kezaeiv/c_wep/dev/dev_rel2.wav
sound/kezaeiv/c_wep/dev/dev_rel3.wav
sound/kezaeiv/c_wep/dstngr/nail_hit_flesh.wav
sound/kezaeiv/c_wep/dstngr/nail_hit_wall.wav
sound/kezaeiv/c_wep/dstngr/spr_nail_hit.wav
sound/kezaeiv/c_wep/dstngr/sting01.wav
sound/kezaeiv/c_wep/dstngr/sting02.wav
sound/kezaeiv/c_wep/dstngr/sting03.wav
sound/kezaeiv/c_wep/dstngr/super_nail.wav
sound/kezaeiv/c_wep/dstngr/tox_hlth01.wav
sound/kezaeiv/c_wep/ehve/roach_blast.wav
sound/kezaeiv/c_wep/frdm/fire.wav
sound/kezaeiv/c_wep/frdm/rkt1.wav
sound/kezaeiv/c_wep/frdm/rotd.wav
sound/kezaeiv/c_wep/frdm/rotu.wav
sound/kezaeiv/c_wep/frdm/srs_boom.wav
sound/kezaeiv/c_wep/frdm/srs_bounce.wav
sound/kezaeiv/c_wep/frdm/srs_cancel.wav
sound/kezaeiv/c_wep/frdm/srs_fire.wav
sound/kezaeiv/c_wep/frdm/srs_prep.wav
sound/kezaeiv/c_wep/frst/ghst1.wav
sound/kezaeiv/c_wep/frst/silenced.wav
sound/kezaeiv/c_wep/frst/ss2_nade.wav
sound/kezaeiv/c_wep/hblst/hb_nova_hit.wav
sound/kezaeiv/c_wep/hblst/hb_plsm.wav
sound/kezaeiv/c_wep/hblst/hb_plsm_blast.wav
sound/kezaeiv/c_wep/knf/k_1.wav
sound/kezaeiv/c_wep/knf/k_2.wav
sound/kezaeiv/c_wep/knf/k_chrg.wav
sound/kezaeiv/c_wep/knf/k_slash1.wav
sound/kezaeiv/c_wep/knf/k_slash2.wav
sound/kezaeiv/c_wep/knf/k_thrw.wav
sound/kezaeiv/c_wep/knf/vcut.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce1.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce2.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce3.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce4.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce5.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit1.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit2.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit3.wav
sound/kezaeiv/c_wep/misc/enrg_hit.wav
sound/kezaeiv/c_wep/misc/exp1.wav
sound/kezaeiv/c_wep/misc/exp2.wav
sound/kezaeiv/c_wep/misc/exp3.wav
sound/kezaeiv/c_wep/misc/exp5.wav
sound/kezaeiv/c_wep/misc/invisibility.wav
sound/kezaeiv/c_wep/misc/item_respawn.wav
sound/kezaeiv/c_wep/misc/noammo.wav
sound/kezaeiv/c_wep/misc/poweruprespawn.wav
sound/kezaeiv/c_wep/misc/protect.wav
sound/kezaeiv/c_wep/misc/protection.wav
sound/kezaeiv/c_wep/misc/quad.wav
sound/kezaeiv/c_wep/misc/quaddamage.wav
sound/kezaeiv/c_wep/misc/samjump.wav
sound/kezaeiv/c_wep/misc/suit.wav
sound/kezaeiv/c_wep/misc/wearoff.wav
sound/kezaeiv/c_wep/mprl/rkt_bounce.wav
sound/kezaeiv/c_wep/mprl/rkt_hit.wav
sound/kezaeiv/c_wep/mprl/rl_shoot.wav
sound/kezaeiv/c_wep/mprl/rl_shoot2.wav
sound/kezaeiv/c_wep/mprl/rl_shoot3.wav
sound/kezaeiv/c_wep/mprl/rl_shoot4.wav
sound/kezaeiv/c_wep/obs/burn1.wav
sound/kezaeiv/c_wep/obs/burn2.wav
sound/kezaeiv/c_wep/obs/flm1.wav
sound/kezaeiv/c_wep/obs/flm2.wav
sound/kezaeiv/c_wep/obs/obs_sg.wav
sound/kezaeiv/c_wep/obs/plsm_nade.wav
sound/kezaeiv/c_wep/par/p_fire.wav
sound/kezaeiv/c_wep/par/p_rail2.wav
sound/kezaeiv/c_wep/par/p_rcht.wav
sound/kezaeiv/c_wep/rptr/r_focus_shot.wav
sound/kezaeiv/c_wep/rptr/r_shot.wav
sound/kezaeiv/c_wep/rptr/r_zoom.wav
sound/kezaeiv/music/oilrig.ogg
sound/kezaeiv/music/vers-us.ogg
sound/kezaeiv/singularity/npc/dusk_shotgun_shot.wav
sound/kezaeiv/singularity/npc/dusk_super_shotgun_shot.wav
sound/kezaeiv/singularity/npc/hgrunt_3shot.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit1.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit2.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit3.wav
sound/kezaeiv/singularity/npc/igi2_dragunov_shot.wav
sound/kezaeiv/singularity/npc/igi2_g36_shot.wav
sound/kezaeiv/singularity/npc/quake3_grenade_shot.wav
sound/kezaeiv/singularity/npc/quake4_plasma_shot.wav
sound/kezaeiv/singularity/npc/starcraft_ghost_rifle.wav
sound/kezaeiv/singularity/npc/tu_fire1.wav
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/squeek/sqk_startled.wav
sound/squeek/sqk_strugglefit1.wav
sound/squeek/sqk_strugglefit2.wav
sound/squeek/sqk_strugglefit3.wav
sound/squeek/sqk_strugglenip1.wav
sound/squeek/sqk_strugglenip2.wav
sound/weapons/357_close.wav
sound/weapons/357_hammerpull.wav
sound/weapons/357_open.wav
sound/weapons/357_reload.wav
sound/weapons/357_shellin.wav
sound/weapons/357_shellsdrop.wav
sound/weapons/alien_draw.wav
sound/weapons/alien_holster.wav
sound/weapons/alien_shake.wav
sound/weapons/alien_sway.wav
sound/weapons/crossbow_bolt.wav
sound/weapons/crossbow_draw.wav
sound/weapons/crossbow_fidget.wav
sound/weapons/crossbow_maghold.wav
sound/weapons/crossbow_magin.wav
sound/weapons/crossbow_magout.wav
sound/weapons/crossbow_magready.wav
sound/weapons/crossbow_pull.wav
sound/weapons/deagle_clipin.wav
sound/weapons/deagle_clipout.wav
sound/weapons/deagle_movement.wav
sound/weapons/deagle_slide.wav
sound/weapons/deagle_slideback.wav
sound/weapons/deagle_sliderelease.wav
sound/weapons/egon_handle1.wav
sound/weapons/egon_handle2.wav
sound/weapons/fidget_2.wav
sound/weapons/fidget_3.wav
sound/weapons/fidget_4.wav
sound/weapons/fidget_6.wav
sound/weapons/gauss_fidget.wav
sound/weapons/glock_clipin.wav
sound/weapons/glock_clipout.wav
sound/weapons/glock_empty.wav
sound/weapons/glock_slideback.wav
sound/weapons/glock_slideforward.wav
sound/weapons/glock_sliderelease.wav
sound/weapons/grenade_pinpull.wav
sound/weapons/grenade_throw.wav
sound/weapons/hks_clic1.wav
sound/weapons/m40a1_clipin.wav
sound/weapons/m40a1_clipout.wav
sound/weapons/m40a1_cliptap.wav
sound/weapons/m41a_load.wav
sound/weapons/M4_boltpull.wav
sound/weapons/M4_clipin.wav
sound/weapons/M4_clipmiddle.wav
sound/weapons/M4_clipout.wav
sound/weapons/M4_cliptap.wav
sound/weapons/medkit_click.wav
sound/weapons/medkit_closed.wav
sound/weapons/medkit_open.wav
sound/weapons/mp5_catch.wav
sound/weapons/MP5_clipinsert1.wav
sound/weapons/MP5_cliprelease1.wav
sound/weapons/mp5_grenadelauncher_1.wav
sound/weapons/mp5_grenadelauncher_2.wav
sound/weapons/mp5_m203_grenade_drop.wav
sound/weapons/mp5_m203_grenade_insert.wav
sound/weapons/reload_done.wav
sound/weapons/RPG_fidget.wav
sound/weapons/rpg_getrocket.wav
sound/weapons/rpg_load.wav
sound/weapons/scock_back.wav
sound/weapons/scock_forward.wav
sound/weapons/spas12_foley.wav
sound/weapons/spas_idle4.wav
sound/weapons/splauncher_draw.wav
sound/weapons/splauncher_idle.wav
sound/weapons/start_reload.wav
sound/weapons/uzi_akimbo_pull1.wav
sound/weapons/uzi_akimbo_pull2.wav
sound/weapons/uzi_boltback.wav
sound/weapons/uzi_clip_connect.wav
sound/weapons/uzi_deploy1.wav
sound/weapons/uzi_reload1.wav
sound/weapons/uzi_reload2.wav
sound/weapons/uzi_reload_left1.wav
sound/weapons/uzi_reload_left2.wav
sound/weapons/uzi_reload_right1.wav
sound/weapons/uzi_reload_right2.wav
sound/weapons/weapon_catch.wav
sound/weapons/weapon_draw.wav
sound/weapons/weapon_holster.wav
sprites/640tfcminigun.spr
sprites/con3/red1.spr
sprites/con3/skarispin.spr
sprites/kezaeiv/c_wep2/ver02/weapon_obsidian.txt
sprites/kezaeiv/c_wep2/weapon_amr.txt
sprites/kezaeiv/c_wep2/weapon_balista.txt
sprites/kezaeiv/c_wep2/weapon_commando.txt
sprites/kezaeiv/c_wep2/weapon_devastator.txt
sprites/kezaeiv/c_wep2/weapon_duality_stinger.txt
sprites/kezaeiv/c_wep2/weapon_freedom_machine.txt
sprites/kezaeiv/c_wep2/weapon_frostbite.txt
sprites/kezaeiv/c_wep2/weapon_kez_partner.txt
sprites/kezaeiv/c_wep2/weapon_mprl.txt
sprites/kezaeiv/c_wep2/weapon_plasma_slayer.txt
sprites/kezaeiv/c_wep2/weapon_raptor_sniper.txt
sprites/kezaeiv/c_wep2/weapon_seeker.txt
sprites/kezaeiv/fx/b-tele_prpl_bl.spr
sprites/kezaeiv/fx/hotglow_crimson.spr
sprites/kezaeiv/fx/hotglow_prpl.spr
sprites/kezaeiv/fx/kz_vcut_bl.spr
sprites/kezaeiv/fx/laser_crshr.spr
sprites/kezaeiv/fx/laser_crshr_cy.spr
sprites/kezaeiv/fx/laser_crshr_wht.spr
sprites/kezaeiv/kezammo.spr
sprites/kezaeiv/kezcrosshairs.spr
sprites/kezaeiv/kezsniper.spr
sprites/kezaeiv/prtl/kz_enter1.spr
sprites/kezaeiv/prtl/kz_exit1.spr
sprites/kezaeiv/xpl/zxlp_blue.spr
sprites/kezaeiv/xpl/zxlp_crimson.spr
sprites/kezaeiv/xpl/zxlp_lila.spr
sprites/kezaeiv/xpl/zxlp_purple.spr
sprites/m41a_off.spr
sprites/m41a_on.spr
sprites/tfchud01.spr
sprites/tfchud02.spr
sprites/weapon_knife.spr
