// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/anachronismbk.tga
gfx/env/anachronismdn.tga
gfx/env/anachronismft.tga
gfx/env/anachronismlf.tga
gfx/env/anachronismrt.tga
gfx/env/anachronismup.tga
models/con3/snowbarnacle.mdl
models/con3/snowdagon2c.mdl
models/con3/snowtree01.mdl
models/kezaeiv/icons/mk_logo_crimson.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn.mdl
models/oghs/cm/npc/massnf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/Tor.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_minigunidle.mdl
models/oghs/cm/wep/p_minigunspin.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/v_bgrap.mdl
models/oghs/cm/wep/v_displacer.mdl
models/oghs/cm/wep/v_minigun.mdl
models/oghs/cm/wep/v_pipe_wrench.mdl
models/oghs/cm/wep/v_spore_launcher.mdl
models/oghs/cm/wep/v_uzi.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_minigun.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
sound/con3/creaks.wav
sound/con3/creepy.wav
sound/con3/dag_step1.wav
sound/con3/dag_step2.wav
sound/con3/dag_step3.wav
sound/con3/dag_step4.wav
sound/con3/foxcry.wav
sound/con3/howl_wind.wav
sound/con3/hugewater.wav
sound/con3/hybrid.wav
sound/con3/ice_cave.wav
sound/con3/morpheus.wav
sound/con3/zipup.wav
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sprites/con3/bi2.spr
sprites/con3/D_TELE1.SPR
sprites/con3/fixflame.spr
sprites/con3/sexysmoke.spr
sprites/con3/skarispin.spr
