// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/kezaeiv/icons/mk_logo_black.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn.mdl
models/oghs/cm/npc/massnf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/Tor.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_minigunidle.mdl
models/oghs/cm/wep/p_minigunspin.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/v_bgrap.mdl
models/oghs/cm/wep/v_displacer.mdl
models/oghs/cm/wep/v_minigun.mdl
models/oghs/cm/wep/v_pipe_wrench.mdl
models/oghs/cm/wep/v_spore_launcher.mdl
models/oghs/cm/wep/v_uzi.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_minigun.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
sound/escape_series/escape1_escape_route.wav
sound/escape_series/escape3/boss.wav
sound/oghs/cs/a!.wav
sound/oghs/cs/bell.wav
sound/oghs/cs/boing.wav
sound/oghs/cs/crit.wav
sound/oghs/cs/csm.wav
sound/oghs/cs/cum.wav
sound/oghs/cs/dross.wav
sound/oghs/cs/fart.wav
sound/oghs/cs/gay.wav
sound/oghs/cs/headshot.wav
sound/oghs/cs/huegh.wav
sound/oghs/cs/pipe.wav
sound/oghs/cs/pui.wav
sound/oghs/cs/slip.wav
sound/oghs/cs/tom2.wav
sound/oghs/cs/wrong.wav
sound/oghs/cs/zzz.wav
sound/oghs/cs03/badbone.wav
