// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

models/fi/hgrunt_fi.mdl
models/fi/sentry.mdl
models/fi/v_displacer.mdl
models/fi/zombie.mdl
models/fi/zombie01.mdl
models/fi/zombie02.mdl
models/fi/zombie03.mdl
models/fi/zombie04.mdl
models/fi/zombie_barney.mdl
models/fi/zombie_soldier.mdl
sound/fi/barney/ba_dooraccess.wav
sound/fi/barney/ba_gamma.wav
sound/fi/barney/ba_scanner.wav
sound/fi/barney/ba_whyyouhere.wav
sound/fi/barney/ba_youneedme.wav
sound/fi/fgrunt/fg_headevac.wav
sound/fi/fgrunt/fg_novfreeman.wav
sound/fi/fgrunt/fg_novhello.wav
sound/fi/fgrunt/fg_novnowaya.wav
sound/fi/fgrunt/fg_novnowayb.wav
sound/fi/fgrunt/fg_shephard1.wav
sound/fi/fgrunt/fg_shephard2.wav
sound/fi/fgrunt/fg_shephard3.wav
sound/fi/fgrunt/tg_power.wav
sound/fi/fgrunt/tg_stuck.wav
sound/fi/fgrunt/tg_zombies.wav
sound/fi/greg/gg_blowgates.wav
sound/fi/greg/gg_cantbelieve.wav
sound/fi/greg/gg_keepseye.wav
sound/fi/greg/gg_ohcrap.wav
sound/fi/hl2/eli_kleinerstop.wav
sound/fi/hl2/eli_whatgoingon.wav
sound/fi/hl2/kl_greatscott.wav
sound/fi/keller/dk_newstuff.wav
sound/fi/kevin/kv_accompany.wav
sound/fi/kevin/kv_antiair.wav
sound/fi/kevin/kv_barney.wav
sound/fi/kevin/kv_blackops.wav
sound/fi/kevin/kv_connect.wav
sound/fi/kevin/kv_contact.wav
sound/fi/kevin/kv_darkness.wav
sound/fi/kevin/kv_death.wav
sound/fi/kevin/kv_doorway.wav
sound/fi/kevin/kv_evac.wav
sound/fi/kevin/kv_freeman.wav
sound/fi/kevin/kv_hearme.wav
sound/fi/kevin/kv_hereiam.wav
sound/fi/kevin/kv_keys.wav
sound/fi/kevin/kv_limaisnear.wav
sound/fi/kevin/kv_lucky.wav
sound/fi/kevin/kv_mantarays.wav
sound/fi/kevin/kv_newobj.wav
sound/fi/kevin/kv_november.wav
sound/fi/kevin/kv_objectives.wav
sound/fi/kevin/kv_onthetrack.wav
sound/fi/kevin/kv_othersci.wav
sound/fi/kevin/kv_radio.wav
sound/fi/kevin/kv_return.wav
sound/fi/kevin/kv_reunite.wav
sound/fi/kevin/kv_rocket.wav
sound/fi/kevin/kv_rosenberg.wav
sound/fi/kevin/kv_satellite.wav
sound/fi/kevin/kv_sectore.wav
sound/fi/kevin/kv_setuptrap.wav
sound/fi/kevin/kv_squadalpha.wav
sound/fi/kevin/kv_theymad.wav
sound/fi/materials.txt
sound/fi/panthereye/pa_idle1.wav
sound/fi/panthereye/pa_idle2.wav
sound/fi/panthereye/pa_idle3.wav
sound/fi/panthereye/pa_idle4.wav
sound/fi/scientist/sc_biobye.wav
sound/fi/scientist/sc_biogamma.wav
sound/fi/scientist/sc_biogarg.wav
sound/fi/scientist/sc_biohello.wav
sound/fi/scientist/sc_bioletsgo.wav
sound/fi/scientist/sc_bioplan.wav
sound/fi/scientist/sc_biotest.wav
sound/fi/scientist/sc_biounlock.wav
sound/fi/scientist/sc_bothwork.wav
sound/fi/scientist/sc_commonenemy.wav
sound/fi/scientist/sc_dangerfire.wav
sound/fi/scientist/sc_dangergas.wav
sound/fi/scientist/sc_dangerrad.wav
sound/fi/scientist/sc_device.wav
sound/fi/scientist/sc_displacer.wav
sound/fi/scientist/sc_getround.wav
sound/fi/scientist/sc_goodluck.wav
sound/fi/scientist/sc_keepgoing.wav
sound/fi/scientist/sc_lockedgates.wav
sound/fi/scientist/sc_military.wav
sound/fi/scientist/sc_satellite.wav
sound/fi/scientist/sc_situation.wav
sound/fi/scientist/sc_woken.wav
sound/fi/scientist/sc_worry.wav
sound/fi/wheelchair/wheelchair_jog.wav
sound/fi/wheelchair/wheelchair_run.wav
sound/fi/wheelchair/wheelchair_walk.wav
sound/fi/worker/wr_leavealone.wav
sound/fi/worker/wr_surface.wav
sound/fi/worker/wr_swarmed.wav
sprites/fi/weapon_knife.txt
sprites/fi/weapon_penguin.txt
