// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/io_newbk.tga
gfx/env/io_newdn.tga
gfx/env/io_newft.tga
gfx/env/io_newlf.tga
gfx/env/io_newrt.tga
gfx/env/io_newup.tga
models/kezaeiv/icons/mk_logo_darkpurple.mdl
models/rngstuff/kuilu/dissection_condor.mdl
models/rngstuff/kuilu/dissection_mo.mdl
models/rngstuff/kuilu/eye.mdl
models/rngstuff/kuilu/guts.mdl
models/rngstuff/kuilu/io_tree.mdl
models/rngstuff/kuilu/k_crate.mdl
models/rngstuff/kuilu/k_dead_trooper.mdl
models/rngstuff/kuilu/npcs/k_b_beakmask.mdl
models/rngstuff/kuilu/npcs/k_b_gasmask.mdl
models/rngstuff/kuilu/npcs/k_barney.mdl
models/rngstuff/kuilu/npcs/k_condor.mdl
models/rngstuff/kuilu/npcs/k_mutant_jackal.mdl
models/rngstuff/kuilu/npcs/k_scientist.mdl
models/rngstuff/kuilu/npcs/k_slave.mdl
models/rngstuff/kuilu/npcs/k_slave_beak.mdl
models/rngstuff/kuilu/npcs/k_slave_big.mdl
models/rngstuff/kuilu/npcs/k_squid.mdl
models/rngstuff/kuilu/npcs/k_squid_beak.mdl
models/rngstuff/kuilu/npcs/k_trooper.mdl
models/rngstuff/kuilu/npcs/k_trooper_beak.mdl
models/rngstuff/kuilu/npcs/k_trooper_bread.mdl
models/rngstuff/kuilu/npcs/k_trooper_metal.mdl
models/rngstuff/kuilu/npcs/k_zombie.mdl
models/rngstuff/kuilu/officechair.mdl
models/rngstuff/kuilu/oldcomputer.mdl
models/rngstuff/kuilu/smalltrees.mdl
models/rngstuff/kuilu/torchpipe.mdl
models/rngstuff/kuilu/treecluster_shrubs.mdl
models/rngstuff/kuilu/weapons/p_colt.mdl
models/rngstuff/kuilu/weapons/p_fiveseven.mdl
models/rngstuff/kuilu/weapons/p_glock.mdl
models/rngstuff/kuilu/weapons/p_knife.mdl
models/rngstuff/kuilu/weapons/p_p228.mdl
models/rngstuff/kuilu/weapons/p_sawedoff.mdl
models/rngstuff/kuilu/weapons/v_colt.mdl
models/rngstuff/kuilu/weapons/v_fiveseven.mdl
models/rngstuff/kuilu/weapons/v_glock.mdl
models/rngstuff/kuilu/weapons/v_knife.mdl
models/rngstuff/kuilu/weapons/v_p228.mdl
models/rngstuff/kuilu/weapons/v_sawedoff.mdl
models/rngstuff/kuilu/weapons/w_ammo_magnum.mdl
models/rngstuff/kuilu/weapons/w_ammo_pistol.mdl
models/rngstuff/kuilu/weapons/w_ammo_shotgun.mdl
models/rngstuff/kuilu/weapons/w_colt.mdl
models/rngstuff/kuilu/weapons/w_fiveseven.mdl
models/rngstuff/kuilu/weapons/w_glock.mdl
models/rngstuff/kuilu/weapons/w_knife.mdl
models/rngstuff/kuilu/weapons/w_p228.mdl
models/rngstuff/kuilu/weapons/w_sawedoff.mdl
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/rng/io/bac_boss_time.ogg
sound/rng/io/counter_secret.ogg
sound/rng/io/counter_secret2.ogg
sound/rng/io/debris/glass_break.ogg
sound/rng/io/debris/metal_break.ogg
sound/rng/io/debris/rock_break.ogg
sound/rng/io/debris/wood_break.ogg
sound/rng/io/destroy_cube.ogg
sound/rng/io/doors/button1.ogg
sound/rng/io/doors/button2.ogg
sound/rng/io/doors/door1.ogg
sound/rng/io/doors/door2.ogg
sound/rng/io/doors/doorstop1.ogg
sound/rng/io/doors/doorstop2.ogg
sound/rng/io/doors/locked.ogg
sound/rng/io/key.ogg
sound/rng/io/laser.ogg
sound/rng/io/misc/item_respawn.ogg
sound/rng/io/misc/pick_ammo.ogg
sound/rng/io/misc/pick_armor.ogg
sound/rng/io/misc/pick_weapon.ogg
sound/rng/io/music/io_bac_loop.ogg
sound/rng/io/music/io_conc_loop.ogg
sound/rng/io/music/io_hallway2_loop.ogg
sound/rng/io/music/io_hallway_loop.ogg
sound/rng/io/music/io_hallway_middle.ogg
sound/rng/io/music/io_main_loop.ogg
sound/rng/io/music/io_outpost_loop.ogg
sound/rng/io/music/io_part1_end.ogg
sound/rng/io/music/io_start.ogg
sound/rng/io/newarea.ogg
sound/rng/io/npc/delugeman/de_man_die.ogg
sound/rng/io/npc/delugeman/de_man_die2.ogg
sound/rng/io/npc/delugeman/de_man_die3.ogg
sound/rng/io/npc/delugeman/de_man_pain.ogg
sound/rng/io/npc/delugeman/de_man_pain2.ogg
sound/rng/io/npc/delugeman/de_man_pain3.ogg
sound/rng/io/npc/slave/slave_alert.ogg
sound/rng/io/npc/slave/slave_alert2.ogg
sound/rng/io/npc/slave/slave_alert3.ogg
sound/rng/io/npc/slave/slave_death.ogg
sound/rng/io/npc/slave/slave_death2.ogg
sound/rng/io/npc/slave/slave_pain.ogg
sound/rng/io/npc/slave/slave_pain2.ogg
sound/rng/io/npc/slave/slave_word1.ogg
sound/rng/io/npc/slave/slave_word2.ogg
sound/rng/io/npc/slave/slave_word3.ogg
sound/rng/io/npc/slave/slave_word4.ogg
sound/rng/io/npc/slave/slave_word5.ogg
sound/rng/io/npc/slave/slave_word6.ogg
sound/rng/io/npc/slave/slave_word7.ogg
sound/rng/io/npc/slave/slave_word8.ogg
sound/rng/io/npc/squid/squid_attack.ogg
sound/rng/io/npc/squid/squid_die.ogg
sound/rng/io/npc/squid/squid_die2.ogg
sound/rng/io/npc/squid/squid_die3.ogg
sound/rng/io/npc/squid/squid_idle.ogg
sound/rng/io/npc/squid/squid_idle2.ogg
sound/rng/io/npc/squid/squid_idle3.ogg
sound/rng/io/npc/squid/squid_idle4.ogg
sound/rng/io/npc/trooper/troop_attack.ogg
sound/rng/io/npc/trooper/troop_death.ogg
sound/rng/io/npc/trooper/troop_death2.ogg
sound/rng/io/npc/trooper/troop_death3.ogg
sound/rng/io/npc/trooper/troop_idle.ogg
sound/rng/io/npc/trooper/troop_idle2.ogg
sound/rng/io/npc/trooper/troop_idle3.ogg
sound/rng/io/npc/trooper/troop_pain.ogg
sound/rng/io/npc/trooper/troop_pain2.ogg
sound/rng/io/npc/trooper/troop_speak.ogg
sound/rng/io/npc/trooper/troop_speak2.ogg
sound/rng/io/npc/trooper/troop_speak3.ogg
sound/rng/io/npc/trooper/troop_speak4.ogg
sound/rng/io/npc/trooper/troop_speak5.ogg
sound/rng/io/npc/trooper/troop_speak6.ogg
sound/rng/io/plat_corner.ogg
sound/rng/io/portal.ogg
sound/rng/io/secret.ogg
sound/rng/io/securitylock.ogg
sound/rng/io/train_accelerate.ogg
sound/rng/io/train_crash_cube.ogg
sound/rng/io/train_crash_wall.ogg
sound/rng/kuilu/weapons/colt_clipin.ogg
sound/rng/kuilu/weapons/colt_clipout.ogg
sound/rng/kuilu/weapons/colt_draw.ogg
sound/rng/kuilu/weapons/colt_fire.ogg
sound/rng/kuilu/weapons/colt_slideback.ogg
sound/rng/kuilu/weapons/colt_slideforward.ogg
sound/rng/kuilu/weapons/fiveseven_clipin.ogg
sound/rng/kuilu/weapons/fiveseven_clipout.ogg
sound/rng/kuilu/weapons/fiveseven_draw.ogg
sound/rng/kuilu/weapons/fiveseven_fire.ogg
sound/rng/kuilu/weapons/fiveseven_slide.ogg
sound/rng/kuilu/weapons/fiveseven_slidepull.ogg
sound/rng/kuilu/weapons/glock_clipin_left.ogg
sound/rng/kuilu/weapons/glock_clipin_right.ogg
sound/rng/kuilu/weapons/glock_clipout.ogg
sound/rng/kuilu/weapons/glock_draw.ogg
sound/rng/kuilu/weapons/glock_fire.ogg
sound/rng/kuilu/weapons/glock_reloadstart.ogg
sound/rng/kuilu/weapons/glock_slide.ogg
sound/rng/kuilu/weapons/knife_draw.ogg
sound/rng/kuilu/weapons/knife_hit.ogg
sound/rng/kuilu/weapons/knife_hit2.ogg
sound/rng/kuilu/weapons/knife_hitwall.ogg
sound/rng/kuilu/weapons/knife_stab.ogg
sound/rng/kuilu/weapons/knife_swing.ogg
sound/rng/kuilu/weapons/knife_swing2.ogg
sound/rng/kuilu/weapons/p228_clipin.ogg
sound/rng/kuilu/weapons/p228_clipout.ogg
sound/rng/kuilu/weapons/p228_draw.ogg
sound/rng/kuilu/weapons/p228_fire.ogg
sound/rng/kuilu/weapons/p228_fire_sil.ogg
sound/rng/kuilu/weapons/p228_silencer_off.ogg
sound/rng/kuilu/weapons/p228_silencer_on.ogg
sound/rng/kuilu/weapons/p228_slide.ogg
sound/rng/kuilu/weapons/p228_slide_sil.ogg
sound/rng/kuilu/weapons/p228_slidepull.ogg
sound/rng/kuilu/weapons/p228_slidepull_sil.ogg
sound/rng/kuilu/weapons/shotgun_close.ogg
sound/rng/kuilu/weapons/shotgun_draw.ogg
sound/rng/kuilu/weapons/shotgun_fire.ogg
sound/rng/kuilu/weapons/shotgun_fire2.ogg
sound/rng/kuilu/weapons/shotgun_open.ogg
sound/rng/kuilu/weapons/shotgun_shell1.ogg
sound/rng/kuilu/weapons/shotgun_shell2.ogg
sound/rng/kuilu/weapons/shotgun_shell_out.ogg
sound/rng/kuilu/weapons/shotgun_shells_eject.ogg
sprites/320hud1.spr
sprites/320hud2.spr
sprites/kuilu/640hud1.spr
sprites/kuilu/640hud10.spr
sprites/kuilu/640hud11.spr
sprites/kuilu/640hud14.spr
sprites/kuilu/640hud15.spr
sprites/kuilu/640hud4.spr
sprites/kuilu/640hud7.spr
sprites/kuilu/crosshairs.spr
sprites/kuilu/firemono.spr
sprites/kuilu/icon_bluekey.spr
sprites/kuilu/icon_colt.spr
sprites/kuilu/icon_fiveseven.spr
sprites/kuilu/icon_glock.spr
sprites/kuilu/icon_greenkey.spr
sprites/kuilu/icon_p228.spr
sprites/kuilu/icon_redkey.spr
sprites/kuilu/icon_shotgun.spr
sprites/kuilu/io_beam.spr
sprites/kuilu/k_eye.spr
sprites/kuilu/k_heart.spr
sprites/kuilu/mist1.spr
sprites/kuilu/mo_portal.spr
sprites/kuilu/weapon_colt.txt
sprites/kuilu/weapon_dualglock.txt
sprites/kuilu/weapon_fiveseven.txt
sprites/kuilu/weapon_knife.txt
sprites/kuilu/weapon_sawedoff.spr
sprites/kuilu/weapon_sawedoff.txt
sprites/kuilu/weapon_usp.txt
