// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

mduty.wad
models/decay/flyer.mdl
models/decay/flyer_gibs.mdl
models/decay/suv.mdl
models/decay/truck_research.mdl
models/opfor/svenhands/v_knife.mdl
models/scmod/alphaunit/geo_bodybag3.mdl
models/scmod/mduty/apc_turret2.mdl
models/scmod/mduty/blwatertow1.mdl
models/scmod/mduty/cactus.mdl
models/scmod/mduty/compost_tower_short.mdl
models/scmod/mduty/eagle.mdl
models/scmod/mduty/fnv_cactus.mdl
models/scmod/mduty/forklift_dummy.mdl
models/scmod/mduty/intro_commanderf.mdl
models/scmod/mduty/intro_memeboycolor.mdl
models/scmod/mduty/m1a1.mdl
models/scmod/mduty/mini_ah1.mdl
models/scmod/mduty/mini_apachef.mdl
models/scmod/mduty/mini_ospreyf.mdl
models/scmod/mduty/s_cactus.mdl
models/scmod/mduty/scientist_opfor.mdl
models/scmod/mduty/trash4.mdl
models/scmod/npcs/barnotis/admer456.mdl
models/scmod/npcs/barnotis/zoner.mdl
models/scmod/npcs/fassn/smolmaid(slyfire12).mdl
models/scmod/npcs/op4torch/memeboycolor(jake).mdl
models/scmod/npcs/zombie/jd.mdl
sound/portal_house/alienflying.wav
sound/scmod/mduty/ambience/f-15.ogg
sound/scmod/mduty/ambience/hawk.ogg
sound/scmod/mduty/ambience/heli_pass.ogg
sound/scmod/mduty/ambience/radiochatter.ogg
sound/scmod/mduty/dialogs/mil_duty1/1memeboy.ogg
sound/scmod/mduty/dialogs/mil_duty1/2memeboy.ogg
sound/scmod/mduty/dialogs/mil_duty1/3smolmaid.ogg
sound/scmod/mduty/dialogs/mil_duty2/sorrounded.ogg
sound/scmod/mduty/dialogs/mil_duty3/1meme.ogg
sound/scmod/mduty/hlinspired.ogg
sound/scmod/mduty/radio/radio1.ogg
sound/scmod/mduty/radio/radio2.ogg
sound/scmod/mduty/radio/radio3.ogg
sound/scmod/mduty/radio/radio4.ogg
sound/scmod/mduty/radio/radio5.ogg
sound/scmod/mduty/radio/radio6.ogg
sound/scmod/mduty/radio/radio7.ogg
sound/scmod/mduty/radio/radio8.ogg
sound/weapons/knife_deploy1.wav
sound/weapons/spas12_foley.wav
sound/weapons/weapon_draw.wav
sound/weapons/weapon_holster.wav
