// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

mduty.wad
models/decay/flyer_gibs.mdl
models/scmod/alab/svensci.mdl
models/scmod/mduty/intro_commanderf.mdl
models/scmod/mduty/intro_regularf.mdl
models/scmod/mduty/intro_sawf.mdl
models/scmod/mduty/mini_ah1.mdl
models/scmod/mduty/mini_apachef.mdl
models/scmod/mduty/mini_ospreyf.mdl
models/scmod/npcs/barnotis/gitrman.mdl
models/scmod/npcs/barnotis/slidje.mdl
models/scmod/npcs/barnotis/soctom.mdl
models/scmod/npcs/barnotis/svenviking.mdl
models/scmod/npcs/barnotis/w00tguy123.mdl
models/scmod/npcs/barnotis/war_nuker.mdl
models/scmod/npcs/bbgarg/deepflame.mdl
models/scmod/npcs/hgrunt/amckern.mdl
models/scmod/npcs/hgrunt/homosapien.mdl
models/scmod/npcs/hgrunt/marphyblack.mdl
models/scmod/npcs/hgrunt/nih_red.mdl
models/scmod/npcs/hgrunt/pumpkin_masher.mdl
models/scmod/npcs/hgrunt/soulescape.mdl
models/scmod/npcs/hwgr/trempler.mdl
models/scmod/npcs/massn/giygas.mdl
models/scmod/npcs/massn/keen.mdl
models/scmod/npcs/massn/puchi.mdl
models/scmod/npcs/massn/rusty.mdl
models/scmod/npcs/massn/sniper.mdl
models/scmod/npcs/massn/spy-warrior.mdl
models/scmod/npcs/op4/adambean.mdl
models/scmod/npcs/op4/gurluas.mdl
models/scmod/npcs/op4/joropito.mdl
models/scmod/npcs/rgrunt/turrican.mdl
sound/gargfoot/whistle.wav
sound/scmod/lajron/dialogs/1sniper_s.ogg
sound/scmod/lajron/dialogs/2sniper.ogg
sound/scmod/lajron/dialogs/3sven.ogg
sound/scmod/lajron/dialogs/4sniper.ogg
sound/scmod/lajron/dialogs/5sci.ogg
sound/scmod/lajron/dialogs/5sven.ogg
sound/scmod/lajron/dialogs/6sniper.ogg
sound/scmod/lajron/viking.ogg
sound/scmod/mduty/ambience/crashed_helo.ogg
sound/scmod/mduty/ambience/f-15.ogg
sound/scmod/mduty/ambience/gatling.ogg
sound/scmod/mduty/ambience/jet_stream.ogg
sound/scmod/mduty/dialogs/milduty/final01.ogg
sound/scmod/mduty/dialogs/milduty/final02.ogg
sound/scmod/mduty/dialogs/milduty/final03.ogg
sound/scmod/mduty/radio/rad1.ogg
sound/scmod/mduty/radio/rad10.ogg
sound/scmod/mduty/radio/rad11.ogg
sound/scmod/mduty/radio/rad2.ogg
sound/scmod/mduty/radio/rad3.ogg
sound/scmod/mduty/radio/rad4.ogg
sound/scmod/mduty/radio/rad5.ogg
sound/scmod/mduty/radio/rad6.ogg
sound/scmod/mduty/radio/rad6_5.ogg
sound/scmod/mduty/radio/rad7.ogg
sound/scmod/mduty/radio/rad8.ogg
sound/scmod/mduty/radio/rad9.ogg
