// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

mduty.wad
models/decay/truck_research.mdl
models/opfor/rope32.mdl
models/scmod/chungo/dead_islave.mdl
models/scmod/mduty/barniel.mdl
models/scmod/mduty/bowl_ramen.mdl
models/scmod/mduty/civ_scientist_hd.mdl
models/scmod/mduty/coffee_cup.mdl
models/scmod/mduty/drabc.mdl
models/scmod/mduty/forklift_dummy.mdl
models/scmod/mduty/greentea.mdl
models/scmod/mduty/mini_ah1.mdl
models/scmod/mduty/mini_apachef.mdl
models/scmod/mduty/wankers/skull_hgrunt.mdl
models/scmod/mduty/wankers/skull_hwgrunt.mdl
models/scmod/mduty/wankers/skull_medic.mdl
models/scmod/npcs/agrunt/therobster.mdl
models/scmod/npcs/barnotis/ascii.mdl
models/scmod/npcs/barnotis/clownishtie002.mdl
models/scmod/npcs/barnotis/deqnq.mdl
models/scmod/npcs/barnotis/gage.mdl
models/scmod/npcs/barnotis/gluem.mdl
models/scmod/npcs/barnotis/gs-ghostdz.mdl
models/scmod/npcs/barnotis/james159.mdl
models/scmod/npcs/barnotis/my_m4n.mdl
models/scmod/npcs/barnotis/philantrop.mdl
models/scmod/npcs/barnotis/princess_sparkles.mdl
models/scmod/npcs/barnotis/vladimir_calhoun_ryan.mdl
models/scmod/npcs/gonome/corporalpunishment.mdl
models/scmod/npcs/hgrunt/lvkas.mdl
models/scmod/npcs/hgrunt/minesettimi.mdl
models/scmod/npcs/hgrunt/viridian.mdl
models/scmod/npcs/hwgr/steel(militarypolice).mdl
models/scmod/npcs/massn/another1.mdl
models/scmod/npcs/massn/liquidator.mdl
models/scmod/npcs/op4/tdw.mdl
models/scmod/npcs/op4torch/nalous.mdl
models/scmod/plat/terror.mdl
models/snd/hgrunt_desert.mdl
sound/scmod/mduty/ambience/train_horn2.ogg
sound/scmod/mduty/dialogs/mil_duty15/1svenradio.ogg
sound/scmod/mduty/dialogs/mil_duty15/2punish.ogg
sound/scmod/mduty/dialogs/mil_duty15/3punishliquidator_r.ogg
sound/scmod/mduty/dialogs/mil_duty15/4sven_r2.ogg
sound/scmod/mduty/dialogs/mil_duty15/5sniper_r.ogg
sound/scmod/mduty/dialogs/milduty/endspeech.ogg
sound/scmod/mduty/dialogs/milduty/endspeech0.ogg
sound/scmod/mduty/dialogs/milduty/evac.ogg
sound/scmod/mduty/fightmusic.ogg
