// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/cubemath/skull.mdl
models/kezaeiv/icons/mk_logo_green.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/crashed_osprey.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn.mdl
models/oghs/cm/npc/massnf.mdl
models/oghs/cm/npc/osprey.mdl
models/oghs/cm/npc/osprey2.mdl
models/oghs/cm/npc/ospreyf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/Tor.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_minigunidle.mdl
models/oghs/cm/wep/p_minigunspin.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_minigun.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
models/oghs/soldier/blkop_apache.mdl
models/oghs/soldier/cleansuit_scientist.mdl
models/oghs/soldier/gordon.mdl
models/oghs/soldier/intro_regular.mdl
models/oghs/soldier/intro_saw.mdl
models/oghs/soldier/p_shotgun.mdl
models/oghs/soldier/v_357.mdl
models/oghs/soldier/v_9mmar.mdl
models/oghs/soldier/v_9mmhandgun.mdl
models/oghs/soldier/v_crossbow.mdl
models/oghs/soldier/v_desert_eagle.mdl
models/oghs/soldier/v_displacer.mdl
models/oghs/soldier/v_egon.mdl
models/oghs/soldier/v_gauss.mdl
models/oghs/soldier/v_grenade.mdl
models/oghs/soldier/v_knife.mdl
models/oghs/soldier/v_m16a2.mdl
models/oghs/soldier/v_m40a1.mdl
models/oghs/soldier/v_medkit.mdl
models/oghs/soldier/v_minigun.mdl
models/oghs/soldier/v_pipe_wrench.mdl
models/oghs/soldier/v_rpg.mdl
models/oghs/soldier/v_satchel.mdl
models/oghs/soldier/v_satchel_radio.mdl
models/oghs/soldier/v_saw.mdl
models/oghs/soldier/v_shotgun.mdl
models/oghs/soldier/v_spore_launcher.mdl
models/oghs/soldier/v_squeak.mdl
models/oghs/soldier/v_tripmine.mdl
models/oghs/soldier/v_uzi.mdl
models/oghs/soldier/w_knife.mdl
models/oghs/soldier/w_shotgun.mdl
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/weapons/desert_eagle_clipin.wav
sound/weapons/desert_eagle_clipout.wav
sound/weapons/sniper_reload1.wav
sound/weapons/sniper_reload2.wav
sound/weapons/sniper_reload4_bolt.wav
