// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

blackops.wad
gfx/env/desert_nitebk.tga
gfx/env/desert_nitedn.tga
gfx/env/desert_niteft.tga
gfx/env/desert_nitelf.tga
gfx/env/desert_nitert.tga
gfx/env/desert_niteup.tga
models/blackops/barney.mdl
models/blackops/bullsquid.mdl
models/blackops/crossbow_bolt.mdl
models/blackops/gman.mdl
models/blackops/grenade.mdl
models/blackops/hassassin.mdl
models/blackops/hgrunt.mdl
models/blackops/houndeye.mdl
models/blackops/islave.mdl
models/blackops/massn.mdl
models/blackops/misc/omegared.mdl
models/blackops/misc/project.mdl
models/blackops/original/p_357.mdl
models/blackops/original/p_9mmar.mdl
models/blackops/original/p_crossbow.mdl
models/blackops/original/p_crowbar.mdl
models/blackops/original/p_grenade.mdl
models/blackops/original/p_rpg.mdl
models/blackops/original/p_shotgun.mdl
models/blackops/original/v_357.mdl
models/blackops/original/v_9mmar.mdl
models/blackops/original/v_9mmhandgun.mdl
models/blackops/original/v_crossbow.mdl
models/blackops/original/v_crowbar.mdl
models/blackops/original/v_grenade.mdl
models/blackops/original/v_medkit.mdl
models/blackops/original/v_rpg.mdl
models/blackops/original/v_shotgun.mdl
models/blackops/original/w_357.mdl
models/blackops/original/w_357ammo.mdl
models/blackops/original/w_357ammobox.mdl
models/blackops/original/w_9mmar.mdl
models/blackops/original/w_9mmarclip.mdl
models/blackops/original/w_9mmhandgun.mdl
models/blackops/original/w_argrenade.mdl
models/blackops/original/w_battery.mdl
models/blackops/original/w_crossbow.mdl
models/blackops/original/w_crossbow_clip.mdl
models/blackops/original/w_crowbar.mdl
models/blackops/original/w_grenade.mdl
models/blackops/original/w_pipe_wrench.mdl
models/blackops/original/w_rpg.mdl
models/blackops/original/w_rpgammo.mdl
models/blackops/original/w_shotbox.mdl
models/blackops/original/w_shotgun.mdl
models/blackops/original/w_suit.mdl
models/blackops/p_357.mdl
models/blackops/p_9mmar.mdl
models/blackops/p_crossbow.mdl
models/blackops/p_crowbar.mdl
models/blackops/p_grenade.mdl
models/blackops/p_m16.mdl
models/blackops/p_medkit.mdl
models/blackops/p_rpg.mdl
models/blackops/p_shotgun.mdl
models/blackops/rpgrocket.mdl
models/blackops/scientist.mdl
models/blackops/shell.mdl
models/blackops/shotgunshell.mdl
models/blackops/v_357.mdl
models/blackops/v_9mmar.mdl
models/blackops/v_9mmhandgun.mdl
models/blackops/v_crossbow.mdl
models/blackops/v_crowbar.mdl
models/blackops/v_grenade.mdl
models/blackops/v_m16a2.mdl
models/blackops/v_medkit.mdl
models/blackops/v_rpg.mdl
models/blackops/v_shotgun.mdl
models/blackops/w_357.mdl
models/blackops/w_357ammo.mdl
models/blackops/w_357ammobox.mdl
models/blackops/w_9mmar.mdl
models/blackops/w_9mmarclip.mdl
models/blackops/w_9mmhandgun.mdl
models/blackops/w_argrenade.mdl
models/blackops/w_battery.mdl
models/blackops/w_crossbow.mdl
models/blackops/w_crossbow_clip.mdl
models/blackops/w_crowbar.mdl
models/blackops/w_grenade.mdl
models/blackops/w_m16.mdl
models/blackops/w_medkit.mdl
models/blackops/w_pmedkit.mdl
models/blackops/w_rpg.mdl
models/blackops/w_rpgammo.mdl
models/blackops/w_shotbox.mdl
models/blackops/w_shotgun.mdl
models/blackops/w_suit.mdl
models/blackops/zombie.mdl
models/oghs/cm/npc/barney.mdl
sound/blackops/ambience/fluorescent.wav
sound/blackops/ambience/mtl_break.wav
sound/blackops/ambience/night2.wav
sound/blackops/ambience/notegrab.wav
sound/blackops/ambience/singledrip.wav
sound/blackops/buttons/button2.wav
sound/blackops/buttons/button7.wav
sound/blackops/buttons/button8.wav
sound/blackops/common/wpn_hudoff.wav
sound/blackops/common/wpn_hudon.wav
sound/blackops/common/wpn_moveselect.wav
sound/blackops/common/wpn_select.wav
sound/blackops/doors/doormove1.wav
sound/blackops/doors/doormove10.wav
sound/blackops/doors/doorstop1.wav
sound/blackops/doors/elev_dr1.wav
sound/blackops/hgrunt/gr_mgun1.wav
sound/blackops/hgrunt/gr_mgun2.wav
sound/blackops/items/gunpickup2.wav
sound/blackops/misc/checkpoint_close.wav
sound/blackops/misc/checkpoint_pulse.wav
sound/blackops/misc/checkpoint_survival.wav
sound/blackops/ops_materials.txt
sound/blackops/player/pl_dirt1.wav
sound/blackops/player/pl_dirt2.wav
sound/blackops/player/pl_dirt3.wav
sound/blackops/player/pl_dirt4.wav
sound/blackops/player/pl_grate1.wav
sound/blackops/player/pl_grate2.wav
sound/blackops/player/pl_grate3.wav
sound/blackops/player/pl_grate4.wav
sound/blackops/player/pl_metal1.wav
sound/blackops/player/pl_metal2.wav
sound/blackops/player/pl_metal3.wav
sound/blackops/player/pl_metal4.wav
sound/blackops/player/pl_slosh1.wav
sound/blackops/player/pl_slosh2.wav
sound/blackops/player/pl_slosh3.wav
sound/blackops/player/pl_slosh4.wav
sound/blackops/player/pl_step1.wav
sound/blackops/player/pl_step2.wav
sound/blackops/player/pl_step3.wav
sound/blackops/player/pl_step4.wav
sound/blackops/player/pl_tile1.wav
sound/blackops/player/pl_tile2.wav
sound/blackops/player/pl_tile3.wav
sound/blackops/player/pl_tile4.wav
sound/blackops/player/pl_tile5.wav
sound/blackops/weapons/dbarrel1.wav
sound/blackops/weapons/hks1.wav
sound/blackops/weapons/hks2.wav
sound/blackops/weapons/hks3.wav
sound/blackops/weapons/pl_gun3.wav
sound/blackops/weapons/sbarrel1.wav
sound/blackops/weapons/scock1.wav
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/weapons/629_shells_land.wav
sound/weapons/g3_boltback.wav
sound/weapons/g3_boltforward.wav
sound/weapons/g3_magin.wav
sound/weapons/g3_magout.wav
sound/weapons/hks_clic1.wav
sound/weapons/m4a1_boltpull.wav
sound/weapons/m4a1_clipin.wav
sound/weapons/m4a1_clipout.wav
sound/weapons/m4a1_deploy.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
