// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/residuallife/baby_icky.mdl
models/residuallife/hassassin.mdl
models/residuallife/icky.mdl
models/residuallife/leech.mdl
models/residuallife/massn.mdl
models/residuallife/nihilanth.mdl
models/residuallife/rustygibs.mdl
models/residuallife/skeleton2_.mdl
models/residuallife/w_bloodly_9mmAR.mdl
models/residuallife/xenocrab.mdl
rl_.wad
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/residuallife/barney/ba_late.wav
sound/residuallife/barney/ba_security2_desk0.wav
sound/residuallife/barney/s02ba_hello.wav
sound/residuallife/barney/s02ba_pl_door.wav
sound/residuallife/barney/sk02_ba_headdown.wav
sound/residuallife/debris/a_teleport.wav
sound/residuallife/fgrunt/ok03b_fg01.wav
sound/residuallife/fvox/inject1.wav
sound/residuallife/gman/gman_intro_talk0.wav
sound/residuallife/gman/intro_gman_tulk1a.wav
sound/residuallife/gman/intro_gman_tulk1b.wav
sound/residuallife/ngrunt/ng_idle0.wav
sound/residuallife/ngrunt/ng_idle1.wav
sound/residuallife/ngrunt/ng_idle2.wav
sound/residuallife/ngrunt/ng_idle3.wav
sound/residuallife/residual_materials.txt
sound/residuallife/scientist/dk01_sci_talk.wav
sound/residuallife/scientist/sc_crazer.wav
