// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/kezaeiv/icons/mk_logo_purple.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/crashed_osprey.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn.mdl
models/oghs/cm/npc/massnf.mdl
models/oghs/cm/npc/osprey.mdl
models/oghs/cm/npc/osprey2.mdl
models/oghs/cm/npc/ospreyf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/tor.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_minigunidle.mdl
models/oghs/cm/wep/p_minigunspin.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/v_bgrap.mdl
models/oghs/cm/wep/v_displacer.mdl
models/oghs/cm/wep/v_minigun.mdl
models/oghs/cm/wep/v_pipe_wrench.mdl
models/oghs/cm/wep/v_spore_launcher.mdl
models/oghs/cm/wep/v_uzi.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_minigun.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
models/shl/hev_sci.mdl
models/shl/hevsci.mdl
models/shl/race.mdl
models/shl/weapons/p_768mmvulcan.mdl
models/shl/weapons/p_p904.mdl
models/shl/weapons/p_plasmagun.mdl
models/shl/weapons/v_768mmvulcan.mdl
models/shl/weapons/v_p904.mdl
models/shl/weapons/v_plasmagun.mdl
models/shl/weapons/w_768ammo.mdl
models/shl/weapons/w_768mmvulcan.mdl
models/shl/weapons/w_p904.mdl
models/shl/weapons/w_plasmaclip.mdl
models/shl/weapons/w_plasmagun.mdl
shl.wad
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/shl/code.ogg
sound/shl/dbarrel1.ogg
sound/shl/hevbarney/hks1.ogg
sound/shl/hevbarney/hks2.ogg
sound/shl/hevbarney/hks3.ogg
sound/shl/hevbarney/sbarrel1.ogg
sound/shl/hevbarney/scock1.ogg
sound/shl/hevsci/run1.ogg
sound/shl/m41a_3round.ogg
sound/shl/m41a_single.ogg
sound/shl/m41aglauncher.ogg
sound/shl/m41aglauncher2.ogg
sound/shl/race/race_alert1.ogg
sound/shl/race/race_alert2.ogg
sound/shl/race/race_die1.ogg
sound/shl/race/race_die2.ogg
sound/shl/race/race_idle1.ogg
sound/shl/race/race_idle2.ogg
sound/shl/race/race_idle3.ogg
sound/shl/race/race_idle4.ogg
sound/shl/race/race_pain1.ogg
sound/shl/race/race_pain2.ogg
sound/shl/race/race_pain3.ogg
sound/shl/race/race_pain4.ogg
sound/shl/race/race_pain5.ogg
sound/shl/scientist/shl2_sci_go.ogg
sound/shl/scientist/shl2_sci_goingon.ogg
sound/shl/scientist/shl2_sci_here.ogg
sound/shl/scientist/shl6_sci_outofhere.ogg
sound/shl/scientist/shl9_sci_destroy.ogg
sound/shl/scientist/shl9_sci_reactor.ogg
sound/shl/scientist/shl_ship_conquerearth.ogg
sound/shl/scientist/shl_ship_destroyship.ogg
sound/shl/scientist/shl_ship_findyourway.ogg
sound/shl/scientist/shl_ship_mothership.ogg
sound/shl/scientist/shl_ship_otherhumans.ogg
sound/shl/scientist/shl_ship_rescuethem.ogg
sound/shl/scientist/shl_ship_stopthem.ogg
sound/shl/scientist/shlwork_sample.ogg
sound/shl/shl_materials.txt
sound/shl/shlloop4.ogg
sound/shl/spf_reload1.ogg
sound/shl/ufo.ogg
sound/shl/ufo_bgm.ogg
sound/shl/ufobeam.ogg
sound/shl/weapons/hw_spin.ogg
sound/shl/weapons/hw_spindown.ogg
sound/shl/weapons/hw_spinup.ogg
sound/shl/weapons/m16burst.ogg
sound/shl/weapons/p904_reload1.ogg
sound/shl/weapons/p904_reload2.ogg
sound/shl/weapons/plasma1.ogg
sound/shl/weapons/plasma2.ogg
sound/shl/weapons/plasma_re.ogg
sprites/gst/extra.spr
sprites/gst/spritefont1.spr
sprites/shl/weapons/640shl1.spr
sprites/shl/weapons/640shl2.spr
sprites/shl/weapons/640shl3.spr
sprites/shl/weapons/640shl4.spr
sprites/shl/weapons/plasma.spr
sprites/shl/weapons/plasmasmall.spr
sprites/shl/weapons/weapon_P904.txt
sprites/shl/weapons/weapon_plasma.txt
sprites/shl/weapons/weapon_vulcan.txt
